--输入输出数据
--IN_CUR_HIVE="sor.CT_T0182_TBSPACN0_H_MID"
--OUT_CUR_HIVE="sor.CT_T0182_TBSPACN0_H"
use sor;

-- Hive数据拉链处理
-- 对私活期存款合约: T0182_TBSPACN0_H

 -- 加入与昨天全量数据，去重
INSERT OVERWRITE TABLE CT_T0182_TBSPACN0_H_MID PARTITION(DATA_TYPE='${log_date}_ALL')
SELECT
    CST_ACCNO,                           -- 客户账号
    DEPAR_ID,                            -- 存款合约编号
    IDCST_ACCNO_NM,                      -- 个人客户账号名称
    CST_ID,                              -- 客户编号
    CSTMGR_USR_ID,                       -- 客户经理用户编号
    PRVT_DEPAR_STCD,                     -- 对私存款合约状态代码
    OPNACC_DT,                           -- 开户日期
    OPNACC_CHNL_ID,                      -- 开户渠道编号
    OPNACC_EMPID,                        -- 开户员工编号
    DPBKINNO,                            -- 开户机构编号
    CNCLACCT_DT,                         -- 销户日期
    CNCLACCT_CHNL_ID,                    -- 销户渠道编号
    CNCLACCT_EMPID,                      -- 销户员工编号
    CNCLACCT_INSID,                      -- 销户机构编号
    SLP_STCD,                            -- 睡眠状态代码
    SLP_DT,                              -- 睡眠日期
    DEP_TFR_SLP_TPCD,                    -- 存款转睡眠类型代码
    DEP_OPNACC_CRDT_TPCD,                -- 存款开户证件类型代码
    PSBK_LOSSRGST_DT,                    -- 存折挂失日期
    DEP_PSBK_STCD,                       -- 存款存折状态代码
    PSWD_WRG_CNT,                        -- 密码出错次数
    PSWD_LOSSRGST_DT,                    -- 密码挂失日期
    DBCRD_AR_ID,                         -- 借记卡合约编号
    DBCRD_CARDNO,                        -- 借记卡卡号
    OPNACC_AMT,                          -- 开户金额
    DEP_OPNACC_CRDT_NO,                  -- 存款开户证件号码
    SETL_ACC_CLCD,                       -- 结算账户分类代码
    P9_START_DATE,                       -- P9开始日期
    P9_END_DATE                          -- P9结束日期
  FROM (SELECT CST_ACCNO, DEPAR_ID, IDCST_ACCNO_NM, CST_ID,
               CSTMGR_USR_ID, PRVT_DEPAR_STCD, OPNACC_DT, OPNACC_CHNL_ID,
               OPNACC_EMPID, DPBKINNO, CNCLACCT_DT, CNCLACCT_CHNL_ID,
               CNCLACCT_EMPID, CNCLACCT_INSID, SLP_STCD, SLP_DT,
               DEP_TFR_SLP_TPCD, DEP_OPNACC_CRDT_TPCD, PSBK_LOSSRGST_DT, DEP_PSBK_STCD,
               PSWD_WRG_CNT, PSWD_LOSSRGST_DT, DBCRD_AR_ID, DBCRD_CARDNO,
               OPNACC_AMT, DEP_OPNACC_CRDT_NO, SETL_ACC_CLCD, P9_START_DATE,
               P9_END_DATE,
               row_number() over (partition by
                   CST_ACCNO, DEPAR_ID, IDCST_ACCNO_NM, CST_ID,
                   CSTMGR_USR_ID, PRVT_DEPAR_STCD, OPNACC_DT, OPNACC_CHNL_ID,
                   OPNACC_EMPID, DPBKINNO, CNCLACCT_DT, CNCLACCT_CHNL_ID,
                   CNCLACCT_EMPID, CNCLACCT_INSID, SLP_STCD, SLP_DT,
                   DEP_TFR_SLP_TPCD, DEP_OPNACC_CRDT_TPCD, PSBK_LOSSRGST_DT, DEP_PSBK_STCD,
                   PSWD_WRG_CNT, PSWD_LOSSRGST_DT, DBCRD_AR_ID, DBCRD_CARDNO,
                   OPNACC_AMT, DEP_OPNACC_CRDT_NO, SETL_ACC_CLCD
                   order by P9_START_DATE
               ) rownum
         FROM CT_T0182_TBSPACN0_H_MID
        WHERE DATA_TYPE in ('${less_7_date}_ALL', '${log_date}_INC',
              '${less_1_date}_INC','${less_2_date}_INC','${less_3_date}_INC','${less_4_date}_INC','${less_5_date}_INC','${less_6_date}_INC')
        ) a
 WHERE a.rownum = 1;

-- Hive并行执行参数设置
set hive.exec.parallel=true;

-- 重建拉链
FROM (
SELECT CST_ACCNO, DEPAR_ID, IDCST_ACCNO_NM, CST_ID,
       CSTMGR_USR_ID, PRVT_DEPAR_STCD, OPNACC_DT, OPNACC_CHNL_ID,
       OPNACC_EMPID, DPBKINNO, CNCLACCT_DT, CNCLACCT_CHNL_ID,
       CNCLACCT_EMPID, CNCLACCT_INSID, SLP_STCD, SLP_DT,
       DEP_TFR_SLP_TPCD, DEP_OPNACC_CRDT_TPCD, PSBK_LOSSRGST_DT, DEP_PSBK_STCD,
       PSWD_WRG_CNT, PSWD_LOSSRGST_DT, DBCRD_AR_ID, DBCRD_CARDNO,
       OPNACC_AMT, DEP_OPNACC_CRDT_NO, SETL_ACC_CLCD, P9_START_DATE,
       lead(P9_START_DATE, 1, '29991231') over (partition by CST_ACCNO, DEPAR_ID
           order by P9_START_DATE) as P9_END_DATE
  FROM CT_T0182_TBSPACN0_H_MID
 WHERE DATA_TYPE='${log_date}_ALL' ) t

-- 插入指定日期的数据
INSERT OVERWRITE TABLE CT_T0182_TBSPACN0_H PARTITION(P9_END_DATE='${log_date}')
SELECT CST_ACCNO, DEPAR_ID, IDCST_ACCNO_NM, CST_ID,
       CSTMGR_USR_ID, PRVT_DEPAR_STCD, OPNACC_DT, OPNACC_CHNL_ID,
       OPNACC_EMPID, DPBKINNO, CNCLACCT_DT, CNCLACCT_CHNL_ID,
       CNCLACCT_EMPID, CNCLACCT_INSID, SLP_STCD, SLP_DT,
       DEP_TFR_SLP_TPCD, DEP_OPNACC_CRDT_TPCD, PSBK_LOSSRGST_DT, DEP_PSBK_STCD,
       PSWD_WRG_CNT, PSWD_LOSSRGST_DT, DBCRD_AR_ID, DBCRD_CARDNO,
       OPNACC_AMT, DEP_OPNACC_CRDT_NO, SETL_ACC_CLCD, P9_START_DATE
 WHERE P9_END_DATE = '${log_date}'

-- 插入指定日期的数据
INSERT OVERWRITE TABLE CT_T0182_TBSPACN0_H PARTITION(P9_END_DATE='${less_1_date}')
SELECT CST_ACCNO, DEPAR_ID, IDCST_ACCNO_NM, CST_ID,
       CSTMGR_USR_ID, PRVT_DEPAR_STCD, OPNACC_DT, OPNACC_CHNL_ID,
       OPNACC_EMPID, DPBKINNO, CNCLACCT_DT, CNCLACCT_CHNL_ID,
       CNCLACCT_EMPID, CNCLACCT_INSID, SLP_STCD, SLP_DT,
       DEP_TFR_SLP_TPCD, DEP_OPNACC_CRDT_TPCD, PSBK_LOSSRGST_DT, DEP_PSBK_STCD,
       PSWD_WRG_CNT, PSWD_LOSSRGST_DT, DBCRD_AR_ID, DBCRD_CARDNO,
       OPNACC_AMT, DEP_OPNACC_CRDT_NO, SETL_ACC_CLCD, P9_START_DATE
 WHERE P9_END_DATE = '${less_1_date}'

-- 插入指定日期的数据
INSERT OVERWRITE TABLE CT_T0182_TBSPACN0_H PARTITION(P9_END_DATE='${less_2_date}')
SELECT CST_ACCNO, DEPAR_ID, IDCST_ACCNO_NM, CST_ID,
       CSTMGR_USR_ID, PRVT_DEPAR_STCD, OPNACC_DT, OPNACC_CHNL_ID,
       OPNACC_EMPID, DPBKINNO, CNCLACCT_DT, CNCLACCT_CHNL_ID,
       CNCLACCT_EMPID, CNCLACCT_INSID, SLP_STCD, SLP_DT,
       DEP_TFR_SLP_TPCD, DEP_OPNACC_CRDT_TPCD, PSBK_LOSSRGST_DT, DEP_PSBK_STCD,
       PSWD_WRG_CNT, PSWD_LOSSRGST_DT, DBCRD_AR_ID, DBCRD_CARDNO,
       OPNACC_AMT, DEP_OPNACC_CRDT_NO, SETL_ACC_CLCD, P9_START_DATE
 WHERE P9_END_DATE = '${less_2_date}'

-- 插入指定日期的数据
INSERT OVERWRITE TABLE CT_T0182_TBSPACN0_H PARTITION(P9_END_DATE='${less_3_date}')
SELECT CST_ACCNO, DEPAR_ID, IDCST_ACCNO_NM, CST_ID,
       CSTMGR_USR_ID, PRVT_DEPAR_STCD, OPNACC_DT, OPNACC_CHNL_ID,
       OPNACC_EMPID, DPBKINNO, CNCLACCT_DT, CNCLACCT_CHNL_ID,
       CNCLACCT_EMPID, CNCLACCT_INSID, SLP_STCD, SLP_DT,
       DEP_TFR_SLP_TPCD, DEP_OPNACC_CRDT_TPCD, PSBK_LOSSRGST_DT, DEP_PSBK_STCD,
       PSWD_WRG_CNT, PSWD_LOSSRGST_DT, DBCRD_AR_ID, DBCRD_CARDNO,
       OPNACC_AMT, DEP_OPNACC_CRDT_NO, SETL_ACC_CLCD, P9_START_DATE
 WHERE P9_END_DATE = '${less_3_date}'

-- 插入指定日期的数据
INSERT OVERWRITE TABLE CT_T0182_TBSPACN0_H PARTITION(P9_END_DATE='${less_4_date}')
SELECT CST_ACCNO, DEPAR_ID, IDCST_ACCNO_NM, CST_ID,
       CSTMGR_USR_ID, PRVT_DEPAR_STCD, OPNACC_DT, OPNACC_CHNL_ID,
       OPNACC_EMPID, DPBKINNO, CNCLACCT_DT, CNCLACCT_CHNL_ID,
       CNCLACCT_EMPID, CNCLACCT_INSID, SLP_STCD, SLP_DT,
       DEP_TFR_SLP_TPCD, DEP_OPNACC_CRDT_TPCD, PSBK_LOSSRGST_DT, DEP_PSBK_STCD,
       PSWD_WRG_CNT, PSWD_LOSSRGST_DT, DBCRD_AR_ID, DBCRD_CARDNO,
       OPNACC_AMT, DEP_OPNACC_CRDT_NO, SETL_ACC_CLCD, P9_START_DATE
 WHERE P9_END_DATE = '${less_4_date}'

-- 插入指定日期的数据
INSERT OVERWRITE TABLE CT_T0182_TBSPACN0_H PARTITION(P9_END_DATE='${less_5_date}')
SELECT CST_ACCNO, DEPAR_ID, IDCST_ACCNO_NM, CST_ID,
       CSTMGR_USR_ID, PRVT_DEPAR_STCD, OPNACC_DT, OPNACC_CHNL_ID,
       OPNACC_EMPID, DPBKINNO, CNCLACCT_DT, CNCLACCT_CHNL_ID,
       CNCLACCT_EMPID, CNCLACCT_INSID, SLP_STCD, SLP_DT,
       DEP_TFR_SLP_TPCD, DEP_OPNACC_CRDT_TPCD, PSBK_LOSSRGST_DT, DEP_PSBK_STCD,
       PSWD_WRG_CNT, PSWD_LOSSRGST_DT, DBCRD_AR_ID, DBCRD_CARDNO,
       OPNACC_AMT, DEP_OPNACC_CRDT_NO, SETL_ACC_CLCD, P9_START_DATE
 WHERE P9_END_DATE = '${less_5_date}'

-- 插入指定日期的数据
INSERT OVERWRITE TABLE CT_T0182_TBSPACN0_H PARTITION(P9_END_DATE='${less_6_date}')
SELECT CST_ACCNO, DEPAR_ID, IDCST_ACCNO_NM, CST_ID,
       CSTMGR_USR_ID, PRVT_DEPAR_STCD, OPNACC_DT, OPNACC_CHNL_ID,
       OPNACC_EMPID, DPBKINNO, CNCLACCT_DT, CNCLACCT_CHNL_ID,
       CNCLACCT_EMPID, CNCLACCT_INSID, SLP_STCD, SLP_DT,
       DEP_TFR_SLP_TPCD, DEP_OPNACC_CRDT_TPCD, PSBK_LOSSRGST_DT, DEP_PSBK_STCD,
       PSWD_WRG_CNT, PSWD_LOSSRGST_DT, DBCRD_AR_ID, DBCRD_CARDNO,
       OPNACC_AMT, DEP_OPNACC_CRDT_NO, SETL_ACC_CLCD, P9_START_DATE
 WHERE P9_END_DATE = '${less_6_date}'

-- 插入当前最新数据
INSERT OVERWRITE TABLE CT_T0182_TBSPACN0_H PARTITION(P9_END_DATE='29991231')
SELECT CST_ACCNO, DEPAR_ID, IDCST_ACCNO_NM, CST_ID,
       CSTMGR_USR_ID, PRVT_DEPAR_STCD, OPNACC_DT, OPNACC_CHNL_ID,
       OPNACC_EMPID, DPBKINNO, CNCLACCT_DT, CNCLACCT_CHNL_ID,
       CNCLACCT_EMPID, CNCLACCT_INSID, SLP_STCD, SLP_DT,
       DEP_TFR_SLP_TPCD, DEP_OPNACC_CRDT_TPCD, PSBK_LOSSRGST_DT, DEP_PSBK_STCD,
       PSWD_WRG_CNT, PSWD_LOSSRGST_DT, DBCRD_AR_ID, DBCRD_CARDNO,
       OPNACC_AMT, DEP_OPNACC_CRDT_NO, SETL_ACC_CLCD, P9_START_DATE
 WHERE P9_END_DATE = '29991231';
