use sor;

-- Hive建表脚本
-- CCBS账户与客户信息整合表: MID_CARD_CUSTOMER_CUR

DROP TABLE IF EXISTS MID_CARD_CUSTOMER_CUR;

CREATE TABLE IF NOT EXISTS MID_CARD_CUSTOMER_CUR(
   -- 帐号
   SA_ACCT_NO                     string,
   -- 开户金额
   SA_OPAC_AMT                    string,
   -- 开户日期
   SA_OPAC_DT                     string,
   -- 记账机构
   SA_RCRD_INSTN_NO               string,
   -- 客户编号
   SA_CUST_NO                     string,
   -- 客户名称
   SA_CUST_NAME                   string,
   -- 联系人编号
   SA_CONNTR_NO                   string,
   -- 销户机构号
   SA_CACCT_INSTN_NO              string,
   -- 销户日期
   SA_CACCT_DT                    string,
   -- 开户柜员号
   SA_OPAC_TL_NO                  string,
   -- 销户柜员号
   SA_CACCT_TL_NO                 string,
   -- 理财卡一户通备付金签约标志
   SA_YHT_SIGN_FLG                string,
   -- 校园卡标志
   SA_XYK_FLG                     string,
   -- 支付限额控制标志
   SA_LMT_CTL_FLG                 string,
   -- 卡号
   SA_CARD_NO                     string,
   -- 综合理财标志
   SA_FS_STS                      string,
   -- 是否贷记卡指定还款帐号
   SA_CCR_FLG                     string,
   -- 卡号
   CR_CRD_NO                      string,
   -- 挂失日期
   CR_DL_DT                       string,
   -- 挂失状态
   CR_DL_STS                      string,
   -- 借贷别
   CR_DR_CR_COD                   string,
   -- 卡种代码
   CR_CRD_TYP_COD                 string,
   -- 卡状态
   CR_CRD_STS                     string,
   -- 客户编号
   CR_CUST_NO                     string,
   -- 营业单位代码
   CR_OPUN_COD                    string,
   -- 主附卡标志
   CR_MNSUB_DRP                   string,
   -- 主卡卡号
   CR_PCRD_NO                     string,
   -- 注销日期
   CR_CNCLC_DT                    string,
   -- 注销状态
   CR_CNCL_STS                    string,
   -- 更改日期
   CR_CHG_GRNTR_DT                string,
   -- 开卡日期
   CR_OPCR_DATE                   string,
   -- 发卡机构号
   CR_APP_NO                      string,
   -- 换卡日期
   CR_CRD_CHG_DT                  string,
   -- 换卡机构号
   CR_CHG_OPUN_COD                string,
   -- #源信息系统代码
   SRC_INF_STM_CD                 string,
   -- #源系统客户编号
   SRCSYS_CST_ID                  string,
   -- 客户编号
   CST_ID                         string,
   -- 个人法定名称
   IDV_LGL_NM                     string,
   -- 证件类型代码
   CRDT_TPCD                      string,
   -- 证件号码
   CRDT_NO                        string,
   -- 出生日期
   BRTH_DT                        string,
   -- 性别代码
   GND_CD                         string,
   -- 国籍代码
   NAT_CD                         string,
   -- 居住国代码
   RSDNC_NAT_CD                   string,
   -- 首选语言代码
   PREF_LNG_CD                    string,
   -- 户籍行政区划代码
   HSHLDRGST_ADIV_CD              string,
   -- 婚姻状况代码
   MAR_STTN_CD                    string,
   -- 子女状况代码
   CHL_STTN_CD                    string,
   -- 民族代码
   ETHNCT_CD                      string,
   -- 宗教信仰代码
   RLG_CD                         string,
   -- 政治面貌代码
   PLTCLPARTY_CD                  string,
   -- 生命周期状态代码
   LCS_CD                         string,
   -- 所属机构编号
   BLNG_INSID                     string,
   -- 建行员工标志
   CCB_EMPE_IND                   string,
   -- 计划财务有效客户标志
   PLN_FNC_EFCT_IND               string,
   -- 重要人士标志
   IMPT_PSNG_IND                  string,
   -- 潜力VIP标志
   PTNL_VIP_IND                   string,
   -- 特殊vip标志
   SPCLVIP_IND                    string,
   -- 系统评定客户等级代码
   STM_EVL_CST_GRD_CD             string,
   -- 手工评定客户等级代码
   MNUL_EVL_CST_GRD_CD            string,
   -- 私人银行客户等级代码
   PRVT_BNK_CST_GRD_CD            string,
   -- 私人银行签约客户标志
   PRVT_BNK_SIGN_CST_IND          string,
   -- 月收入金额
   MO_INCMAM                      string,
   -- 客户经理编号
   CSTMGR_ID                      string,
   -- 最佳联系电话
   BEST_CTC_TEL                   string,
   -- 企业高级管理人员标志
   ENTP_ADV_MGTPPL_IND            string,
   -- 企业实际控制人标志
   ENTP_ACT_CTRL_PSN_IND          string,
   -- 企业法人标志
   ENLGPS_IND                     string,
   -- 非居民标志
   NON_RSDNT_IND                  string,
   -- 工作单位性质代码
   WRK_UNIT_CHAR_CD               string
)
STORED AS ORC;

