use sor;

-- Hive建表脚本
-- 线上批量交易流水表: T0291_BTH_ONL_TXN_JNL_A

-- 外部表
DROP TABLE IF EXISTS EXT_T0291_BTH_ONL_TXN_JNL_A;

CREATE EXTERNAL TABLE IF NOT EXISTS EXT_T0291_BTH_ONL_TXN_JNL_A(
    POS_OFSTBAL_DT            string comment 'POS轧账日期',
    TMNLTOACCEFSRCRDTRCNO     string comment '终端待入账资金汇总记录流水号',
    DOMNINSTPRFDAERRTRCNO     string comment '管辖机构分润入账结果记录流水号',
    APNTINSTPRFDAERRTRCNO     string comment '指定机构分润入账结果记录流水号',
    EBNK_VCHR_NO              string comment '网银凭证号',
    USR_ID_NO                 string comment '用户识别号',
    RFNDTP_CD                 string comment '退款类型代码',
    JNT_CO_USR_NO             string comment '联名公司用户号',
    MRCHCMSN_TPCD             string comment '商户手续费类型代码',
    CLRG_TXN_CD               string comment '清算交易码',
    TXN_CD_CHN_NM             string comment '交易代码中文名称',
    ACQ_TRCNO                 string comment '收单流水号',
    ACQ_ORI_TRCNO             string comment '收单原流水号',
    P1_FRT_STM_TXNSRLNO       string comment 'P1前置系统交易流水号',
    P1FRTSTM_ORI_TXNSRLNO     string comment 'P1前置系统原交易流水号',
    UNNPY_TXN_KEY_VAL         string comment '银联交易Key值',
    UNNPY_ORI_TXN_KEY_VAL     string comment '银联原交易Key值',
    CLRG_STM_DT_TM            string comment '清算系统日期时间',
    CLRG_TXN_PCSST_CD         string comment '清算交易处理状态代码',
    CLRG_UDO_STCD             string comment '清算撤销状态代码',
    CLRG_RVRS_STCD            string comment '清算冲正状态代码',
    OBCRD_CLRG_INDCD          string comment '外卡清算标志代码',
    MRCH_CLRG_MODE_CD         string comment '商户清算模式代码',
    APLYFORLOAN_STCD          string comment '请款状态代码',
    ACQ_FNDS_CLRG_DT          string comment '收单资金清算日期',
    CARDNO                    string comment '卡号',
    CCYCD                     string comment '币种代码',
    TXNAMT                    string comment '交易金额',
    RBT_SET_MTDCD             string comment '回扣设置方式代码',
    PER_MRCH_ACQ_HDCG_AMT     string comment '单笔商户收单手续费金额',
    CRDHLDR_ACC_STRD_SN       string comment '持卡人账子交易序号',
    MRCH_ACC_STRD_SN          string comment '商户账子交易序号',
    SETL_ACCNO_IND            string comment '结算账号标志',
    PERMRCHACQ_CMSICM_AMT     string comment '单笔商户收单手续费收入金额',
    STM_TRCK_NO               string comment '系统跟踪号',
    TXN_SND_TM                string comment '交易发送时间',
    MRCH_TP_ECD               string comment '商户类型编码',
    ACQ_INST_IDR_CD           string comment '收单机构标识码',
    TRSMT_INST_IDR_CD         string comment '转发机构标识码',
    RTRVL_REF_NO              string comment '检索参考号',
    CRD_AHN_CD                string comment '卡授权码',
    EDCRDMCHN_TMNL_IDR_CD     string comment '受卡机终端标识码',
    ED_CRD_PRTY_IDR_CD        string comment '受卡方标识码',
    RCV_INST_IDR_CD           string comment '接收机构标识码',
    POS_ID                    string comment 'POS编号',
    CLRG_BTNO_ID              string comment '清算批次编号',
    SYS_RESP_CODE             string comment '响应码',
    SYS_RESP_DESC             string comment '服务响应描述',
    MRCH_DCN_COLL_MTDCD       string comment '商户回佣收取方式代码',
    PER_MRCH_ACQ_CLRGAMT      string comment '单笔商户收单清算金额',
    POS_OFSTBAL_IND           string comment 'POS轧账标志',
    OFSTBAL_INDCD             string comment '轧账标志代码',
    ACQ_BTCH_DTSWH_DT         string comment '收单批量日切日期',
    CRD_ATTR_BMP_DEF_ID       string comment '卡属性位图定义编号',
    ACQ_CMSNCHRGRATE_TPCD     string comment '收单扣率类型代码',
    MRCH_TXN_RSK_STCD         string comment '商户交易风险状态代码',
    RSK_RLSE_DT               string comment '风险释放日期',
    ACQ_CLRG_INSNO            string comment '收单清算机构号',
    INST_PRFDV_STCD           string comment '机构分润状态代码',
    CRDHLDR_ACC_PCSST_CD      string comment '持卡人账处理状态代码',
    PCSGCRDHLDRACCSCSVCID     string comment '处理持卡人账的组件服务ID',
    PCSGMRCHACCS_TXN_STCD     string comment '处理商户账的交易状态代码',
    PCSGMRCHACCSCMPTSVCID     string comment '处理商户账的组件服务ID',
    PCSGMRCHCMSNSTXN_STCD     string comment '处理商户手续费的交易状态代码',
    PCSGHDCGACCSCMPTSVCID     string comment '处理手续费账的组件服务ID',
    SETL_ACCNO                string comment '结算账号',
    DSTCRD_ISSUBNK_INSNO      string comment '内卡发卡行机构号',
    CNTER_ID                  string comment '柜台编号',
    SPINSTM_TXN_ORDR_NO       string comment '专项分期交易订单号',
    INSTM_PRD_NUM             string comment '分期期数',
    INSTM_TPCD                string comment '分期类型代码',
    PART_RETGDS_TPCD          string comment '部分退货类型代码',
    SYS_EVT_TRACE_ID          string comment '全局事件跟踪号(流水号)',
    ORIOVRLSTTNEV_TRCK_NO     string comment '原全局事件跟踪号',
    ISSUBNK_NTW_INDCD         string comment '发卡行网络标志代码',
    ITTPARTY_MNPLT_DT_TM      string comment '发起方操作日期时间',
    ITTPARTYORIMNPLTDT_TM     string comment '发起方原操作日期时间',
    UNNPY_COST                string comment '银联成本',
    PERMRCHACQCHLDCMSNAMT     string comment '单笔商户收单持卡人手续费金额',
    HDCG_ACC_STRD_SN          string comment '手续费账子交易序号',
    DCN_SETL_ACC_CGYCD        string comment '回佣结算账户类别代码',
    DCN_EXG_AR_ACCNO          string comment '回佣交换合约账号',
    ITTPARTY_PLTFRM_TRCNO     string comment '发起方平台流水号',
    CCBINS_ID                 string comment '建行机构编号',
    SYS_SND_SERIAL_NO         string comment '子交易序号',
    SYS_TX_TYPE               string comment '服务种类',
    MRCH_GBNK_INSNO           string comment '分行机构号',
    APLY_TXN_STFF_ID          string comment '申请交易人员编号',
    SYS_TX_CODE               string comment '交易服务编码',
    TXN_ITT_CHNL_CGY_CODE     string comment '交易发起渠道类别',
    TXN_ITT_CHNL_ID           string comment '交易发起渠道编号',
    EMRCH_MRCH_TPCD           string comment '电商商户类型代码',
    TXNDATA_TBL_SN            string comment '交易数据表序号',
    STMGENACTACC_PCSG_IND     string comment '系统生成会计账处理标志',
    MRCH_BLNG_DEPT_CD         string comment '商户所属部门代码',
    TXN_FEE_CGY_CD            string comment '交易费类别码',
    CRDHLDR_TXN_TP_CD         string comment '持卡人交易类型码',
    VISA_LV2_MRCH_NO          string comment 'VISA二级商户号',
    LV2_MRCH_NM               string comment '二级商户名称',
    ORI_STRD_SN               string comment '原子交易序号',
    ORI_SVC_CTLG              string comment '原服务种类',
    PERMRCHOBCATOCLRGHDCG     string comment '单笔商户外卡收单待清算手续费',
    PERMRCHOBCATO_CLRGAMT     string comment '单笔商户外卡收单待清算金额',
    SVCPNTCARDNOINPTMODCD     string comment '服务点卡号输入方式码',
    SVCPNTPSWDINPT_MOD_CD     string comment '服务点密码输入方式码',
    TMNL_RD_CPY_VAL           string comment '终端读取能力取值',
    ACT_ADJAC_SETNO_VALST     string comment '会计平账套号取值',
    STM_PCS_DT                string comment '系统处理日期',
    ACPT_LND_TXN_DT           string comment '受理地交易日期',
    ACPT_LND_TXN_TM           string comment '受理地交易时间',
    EXEC_TOT_TM               string comment '执行总时间',
    ITT_NODE_ID               string comment '发起节点编号',
    AVY_NODE_ID               string comment '活动节点编号',
    PARM_TECH_EFF_RQD_TM      string comment '参数技术生效所需时间',
    PLTFRM_TXN_CD             string comment '平台交易码',
    ERR_SEC_ID                string comment '错误源安全节点编号',
    COL_MGT_MCHN_ID           string comment '采集管理机器编号',
    ICCD_SEQ_NO               string comment 'IC卡序列号',
    CNTPR_ACCNO               string comment '交易对手账号',
    CNTPR_ACCNM               string comment '交易对手账户名称',
    P9_SPLIT_BRANCH_CD        string comment '来源行',
    P9_DATA_DATE              string comment 'P9数据日期',
    P9_BATCH_NUMBER           string comment '',
    P9_DEL_FLAG               string comment '',
    P9_DEL_DATE               string comment '',
    P9_DEL_BATCH              string comment '',
    P9_JOB_NAME               string comment ''
)
PARTITIONED BY (LOAD_DATE string)
STORED AS TEXTFILE;

-- ORC内部表，节约存储空间
DROP TABLE IF EXISTS INN_T0291_BTH_ONL_TXN_JNL_A;

CREATE TABLE IF NOT EXISTS INN_T0291_BTH_ONL_TXN_JNL_A(
    POS_OFSTBAL_DT            string comment 'POS轧账日期',
    EBNK_VCHR_NO              string comment '网银凭证号',
    USR_ID_NO                 string comment '用户识别号',
    TXN_CD_CHN_NM             string comment '交易代码中文名称',
    CARDNO                    string comment '卡号',
    CCYCD                     string comment '币种代码',
    TXNAMT                    string comment '交易金额',
    TXN_SND_TM                string comment '交易发送时间',
    POS_ID                    string comment 'POS编号',
    SYS_RESP_CODE             string comment '响应码',
    SYS_RESP_DESC             string comment '服务响应描述',
    SYS_EVT_TRACE_ID          string comment '全局事件跟踪号(流水号)',
    CCBINS_ID                 string comment '建行机构编号',
    SYS_TX_CODE               string comment '交易服务编码',
    TXN_ITT_CHNL_CGY_CODE     string comment '交易发起渠道类别',
    TXN_ITT_CHNL_ID           string comment '交易发起渠道编号',
    EMRCH_MRCH_TPCD           string comment '电商商户类型代码',
    VISA_LV2_MRCH_NO          string comment 'VISA二级商户号',
    LV2_MRCH_NM               string comment '二级商户名称',
    CNTPR_ACCNO               string comment '交易对手账号',
    CNTPR_ACCNM               string comment '交易对手账户名称'
)
PARTITIONED BY (P9_DATA_DATE string)
STORED AS ORC;
