use sor;

-- Hive建表脚本
-- 对私活期存款合约: T0182_TBSPACN0_H

-- 外部表
DROP TABLE IF EXISTS EXT_T0182_TBSPACN0_H;

CREATE EXTERNAL TABLE IF NOT EXISTS EXT_T0182_TBSPACN0_H(
    MULTI_TENANCY_ID          string comment '多实体标识',
    APL_PRTN_NO               string comment '应用分区号',
    CST_ACCNO                 string comment '客户账号',
    DEPAR_SN                  string comment '存款合约序号',
    DEPAR_ID                  string comment '存款合约编号',
    IDCST_ACCNO_NM            string comment '个人客户账号名称',
    ASPD_ASB_VNO              string comment '可售产品装配版本号',
    ASPD_ID                   string comment '可售产品编号',
    FNDS_USE_CD               string comment '资金用途代码',
    CST_ID                    string comment '客户编号',
    CSTMGR_USR_ID             string comment '客户经理用户编号',
    PRVT_DEPAR_STCD           string comment '对私存款合约状态代码',
    SEAL_CRD_CFINF_ID         string comment '印鉴卡认证信息编号',
    OPNACC_DT                 string comment '开户日期',
    OPNACC_CHNL_ID            string comment '开户渠道编号',
    OPNACC_EMPID              string comment '开户员工编号',
    DPBKINNO                  string comment '开户机构编号',
    LDGR_INSID                string comment '核算机构编号',
    OPNACC_CHNL_TPCD          string comment '开户渠道类型代码',
    CNCLACCT_CHNL_TPCD        string comment '销户渠道类型代码',
    CNCLACCT_DT               string comment '销户日期',
    CNCLACCT_CHNL_ID          string comment '销户渠道编号',
    CNCLACCT_EMPID            string comment '销户员工编号',
    CNCLACCT_INSID            string comment '销户机构编号',
    RCVPY_CTRL_STCD           string comment '收付控制状态代码',
    ORI_RCVPY_CTRL_STCD       string comment '原收付控制状态代码',
    SLP_STCD                  string comment '睡眠状态代码',
    SLP_DT                    string comment '睡眠日期',
    DEP_TFR_SLP_TPCD          string comment '存款转睡眠类型代码',
    SLP_SWTBCK_APRV_STCD      string comment '睡眠转回审批状态代码',
    DEP_ALRDY_PRT_DTL_NUM     string comment '存款已打印明细数',
    DEP_ALRDY_PRT_PG_NUM      string comment '存款已打印页数',
    ALRDY_PRT_LNUM            string comment '已打印行数',
    DEP_VERF_MTDCD            string comment '存款校验方式代码',
    FCS_SIGN_NUM              string comment '关注签约数量',
    PD_SALE_FTA_CD            string comment '产品销售自贸区代码',
    DEP_OPNACC_CRDT_TPCD      string comment '存款开户证件类型代码',
    DEP_BKLTNO                string comment '存款存折册号',
    PSBK_LOSSRGST_DT          string comment '存折挂失日期',
    DEP_PSBK_STCD             string comment '存款存折状态代码',
    PRVTDEPSIGNTPLIST_VAL     string comment '对私存款签约类型列表值',
    LNCRDREPYACCNOSIGNNUM     string comment '贷记卡还款账号签约数量',
    IDV_FRNCY_ACCHAR_CD       string comment '个人外币账户性质代码',
    CST_PINOFFSET_VAL         string comment '客户PINOFFSET值',
    DEP_PSWD_STCD             string comment '存款密码状态代码',
    DVV_SAFE_INDX_ID          string comment 'DVV安全索引编号',
    DEP_ACCHAR_CD             string comment '存款账户性质代码',
    CSHEX_CHAR_CD             string comment '钞汇性质代码',
    PSWD_WRG_CNT              string comment '密码出错次数',
    PSWD_LOSSRGST_DT          string comment '密码挂失日期',
    SUSP_4_BIT_PSWD_IND       string comment '疑似4位密码标志',
    DBCRD_AR_ID               string comment '借记卡合约编号',
    DBCRD_CARDNO              string comment '借记卡卡号',
    DEP_PSBK_PRT_NO           string comment '存款存折印刷号',
    UNVSDEP_SCOP_CD           string comment '通存范围代码',
    UNVSWD_SCOP_CD            string comment '通兑范围代码',
    CST_ACCNM_VLD_IND         string comment '客户户名验证标志',
    INTAR_IND                 string comment '计息标志',
    OPNACC_AMT                string comment '开户金额',
    CUR_DTL_MAX_SN            string comment '当前明细最大序号',
    CUR_DTL_LAST_TXN_DT       string comment '当前明细最后交易日期',
    INTDYIDVCACNYENCMTAMT     string comment '当日个人活期账户人民币取现金额',
    INTDYIDVCAUSDENCMTAMT     string comment '当日个人活期账户美元取现金额',
    INTDY_INT_DTL_SN          string comment '当日首笔明细序号',
    DEP_OPNACC_CRDT_NO        string comment '存款开户证件号码',
    ACC_RSK_GRD_TPCD          string comment '账户风险等级类型代码',
    SETL_ACC_CLCD             string comment '结算账户分类代码',
    LAST_UDT_OPRGDAY          string comment '最后更新营业日',
    TMS                       string comment '时间戳',
    P9_SPLIT_BRANCH_CD        string comment '来源行',
    P9_START_DATE             string comment 'P9开始日期',
    P9_START_BATCH            string comment '',
    P9_END_DATE               string comment 'P9结束日期',
    P9_END_BATCH              string comment '',
    P9_DEL_FLAG               string comment '',
    P9_JOB_NAME               string comment ''
)
PARTITIONED BY (LOAD_DATE string)
STORED AS TEXTFILE;

-- ORC内部表，节约存储空间
DROP TABLE IF EXISTS INN_T0182_TBSPACN0_H;

CREATE TABLE IF NOT EXISTS INN_T0182_TBSPACN0_H(
    MULTI_TENANCY_ID          string comment '多实体标识',
    APL_PRTN_NO               string comment '应用分区号',
    CST_ACCNO                 string comment '客户账号',
    DEPAR_SN                  string comment '存款合约序号',
    DEPAR_ID                  string comment '存款合约编号',
    IDCST_ACCNO_NM            string comment '个人客户账号名称',
    ASPD_ASB_VNO              string comment '可售产品装配版本号',
    ASPD_ID                   string comment '可售产品编号',
    FNDS_USE_CD               string comment '资金用途代码',
    CST_ID                    string comment '客户编号',
    CSTMGR_USR_ID             string comment '客户经理用户编号',
    PRVT_DEPAR_STCD           string comment '对私存款合约状态代码',
    SEAL_CRD_CFINF_ID         string comment '印鉴卡认证信息编号',
    OPNACC_DT                 string comment '开户日期',
    OPNACC_CHNL_ID            string comment '开户渠道编号',
    OPNACC_EMPID              string comment '开户员工编号',
    DPBKINNO                  string comment '开户机构编号',
    LDGR_INSID                string comment '核算机构编号',
    OPNACC_CHNL_TPCD          string comment '开户渠道类型代码',
    CNCLACCT_CHNL_TPCD        string comment '销户渠道类型代码',
    CNCLACCT_DT               string comment '销户日期',
    CNCLACCT_CHNL_ID          string comment '销户渠道编号',
    CNCLACCT_EMPID            string comment '销户员工编号',
    CNCLACCT_INSID            string comment '销户机构编号',
    RCVPY_CTRL_STCD           string comment '收付控制状态代码',
    ORI_RCVPY_CTRL_STCD       string comment '原收付控制状态代码',
    SLP_STCD                  string comment '睡眠状态代码',
    SLP_DT                    string comment '睡眠日期',
    DEP_TFR_SLP_TPCD          string comment '存款转睡眠类型代码',
    SLP_SWTBCK_APRV_STCD      string comment '睡眠转回审批状态代码',
    DEP_ALRDY_PRT_DTL_NUM     string comment '存款已打印明细数',
    DEP_ALRDY_PRT_PG_NUM      string comment '存款已打印页数',
    ALRDY_PRT_LNUM            string comment '已打印行数',
    DEP_VERF_MTDCD            string comment '存款校验方式代码',
    FCS_SIGN_NUM              string comment '关注签约数量',
    PD_SALE_FTA_CD            string comment '产品销售自贸区代码',
    DEP_OPNACC_CRDT_TPCD      string comment '存款开户证件类型代码',
    DEP_BKLTNO                string comment '存款存折册号',
    PSBK_LOSSRGST_DT          string comment '存折挂失日期',
    DEP_PSBK_STCD             string comment '存款存折状态代码',
    PRVTDEPSIGNTPLIST_VAL     string comment '对私存款签约类型列表值',
    LNCRDREPYACCNOSIGNNUM     string comment '贷记卡还款账号签约数量',
    IDV_FRNCY_ACCHAR_CD       string comment '个人外币账户性质代码',
    CST_PINOFFSET_VAL         string comment '客户PINOFFSET值',
    DEP_PSWD_STCD             string comment '存款密码状态代码',
    DVV_SAFE_INDX_ID          string comment 'DVV安全索引编号',
    DEP_ACCHAR_CD             string comment '存款账户性质代码',
    CSHEX_CHAR_CD             string comment '钞汇性质代码',
    PSWD_WRG_CNT              string comment '密码出错次数',
    PSWD_LOSSRGST_DT          string comment '密码挂失日期',
    SUSP_4_BIT_PSWD_IND       string comment '疑似4位密码标志',
    DBCRD_AR_ID               string comment '借记卡合约编号',
    DBCRD_CARDNO              string comment '借记卡卡号',
    DEP_PSBK_PRT_NO           string comment '存款存折印刷号',
    UNVSDEP_SCOP_CD           string comment '通存范围代码',
    UNVSWD_SCOP_CD            string comment '通兑范围代码',
    CST_ACCNM_VLD_IND         string comment '客户户名验证标志',
    INTAR_IND                 string comment '计息标志',
    OPNACC_AMT                string comment '开户金额',
    CUR_DTL_MAX_SN            string comment '当前明细最大序号',
    CUR_DTL_LAST_TXN_DT       string comment '当前明细最后交易日期',
    INTDYIDVCACNYENCMTAMT     string comment '当日个人活期账户人民币取现金额',
    INTDYIDVCAUSDENCMTAMT     string comment '当日个人活期账户美元取现金额',
    INTDY_INT_DTL_SN          string comment '当日首笔明细序号',
    DEP_OPNACC_CRDT_NO        string comment '存款开户证件号码',
    ACC_RSK_GRD_TPCD          string comment '账户风险等级类型代码',
    SETL_ACC_CLCD             string comment '结算账户分类代码',
    LAST_UDT_OPRGDAY          string comment '最后更新营业日',
    TMS                       string comment '时间戳',
    P9_START_DATE             string comment 'P9开始日期',
    P9_END_DATE               string comment 'P9结束日期'
)
PARTITIONED BY (LOAD_DATE string)
STORED AS ORC;

-- 拉链表中间数据
DROP TABLE IF EXISTS CT_T0182_TBSPACN0_H_MID;

CREATE TABLE IF NOT EXISTS CT_T0182_TBSPACN0_H_MID (
    CST_ACCNO                 string comment '客户账号',
    DEPAR_ID                  string comment '存款合约编号',
    IDCST_ACCNO_NM            string comment '个人客户账号名称',
    CST_ID                    string comment '客户编号',
    CSTMGR_USR_ID             string comment '客户经理用户编号',
    PRVT_DEPAR_STCD           string comment '对私存款合约状态代码',
    OPNACC_DT                 string comment '开户日期',
    OPNACC_CHNL_ID            string comment '开户渠道编号',
    OPNACC_EMPID              string comment '开户员工编号',
    DPBKINNO                  string comment '开户机构编号',
    CNCLACCT_DT               string comment '销户日期',
    CNCLACCT_CHNL_ID          string comment '销户渠道编号',
    CNCLACCT_EMPID            string comment '销户员工编号',
    CNCLACCT_INSID            string comment '销户机构编号',
    SLP_STCD                  string comment '睡眠状态代码',
    SLP_DT                    string comment '睡眠日期',
    DEP_TFR_SLP_TPCD          string comment '存款转睡眠类型代码',
    DEP_OPNACC_CRDT_TPCD      string comment '存款开户证件类型代码',
    PSBK_LOSSRGST_DT          string comment '存折挂失日期',
    DEP_PSBK_STCD             string comment '存款存折状态代码',
    PSWD_WRG_CNT              string comment '密码出错次数',
    PSWD_LOSSRGST_DT          string comment '密码挂失日期',
    DBCRD_AR_ID               string comment '借记卡合约编号',
    DBCRD_CARDNO              string comment '借记卡卡号',
    OPNACC_AMT                string comment '开户金额',
    DEP_OPNACC_CRDT_NO        string comment '存款开户证件号码',
    SETL_ACC_CLCD             string comment '结算账户分类代码',
    P9_START_DATE             string comment 'P9开始日期',
    P9_END_DATE               string comment 'P9结束日期'
)
PARTITIONED BY (DATA_TYPE string)
STORED AS ORC;

-- 最终拉链表
DROP TABLE IF EXISTS CT_T0182_TBSPACN0_H;

CREATE TABLE IF NOT EXISTS CT_T0182_TBSPACN0_H (
    CST_ACCNO                 string comment '客户账号',
    DEPAR_ID                  string comment '存款合约编号',
    IDCST_ACCNO_NM            string comment '个人客户账号名称',
    CST_ID                    string comment '客户编号',
    CSTMGR_USR_ID             string comment '客户经理用户编号',
    PRVT_DEPAR_STCD           string comment '对私存款合约状态代码',
    OPNACC_DT                 string comment '开户日期',
    OPNACC_CHNL_ID            string comment '开户渠道编号',
    OPNACC_EMPID              string comment '开户员工编号',
    DPBKINNO                  string comment '开户机构编号',
    CNCLACCT_DT               string comment '销户日期',
    CNCLACCT_CHNL_ID          string comment '销户渠道编号',
    CNCLACCT_EMPID            string comment '销户员工编号',
    CNCLACCT_INSID            string comment '销户机构编号',
    SLP_STCD                  string comment '睡眠状态代码',
    SLP_DT                    string comment '睡眠日期',
    DEP_TFR_SLP_TPCD          string comment '存款转睡眠类型代码',
    DEP_OPNACC_CRDT_TPCD      string comment '存款开户证件类型代码',
    PSBK_LOSSRGST_DT          string comment '存折挂失日期',
    DEP_PSBK_STCD             string comment '存款存折状态代码',
    PSWD_WRG_CNT              string comment '密码出错次数',
    PSWD_LOSSRGST_DT          string comment '密码挂失日期',
    DBCRD_AR_ID               string comment '借记卡合约编号',
    DBCRD_CARDNO              string comment '借记卡卡号',
    OPNACC_AMT                string comment '开户金额',
    DEP_OPNACC_CRDT_NO        string comment '存款开户证件号码',
    SETL_ACC_CLCD             string comment '结算账户分类代码',
    P9_START_DATE             string comment 'P9开始日期'
)
PARTITIONED BY (P9_END_DATE string)
STORED AS ORC;
