#field_en, field_cn, field_type, field_length, field_is_pk, field_is_dk, field_to_ctbase, index_describe, index_function, index_split, field_filter
table_cn = '渠道签约信息痕迹'
field_array = [
    ('FLOW_NO', '交易流水号', '', ''),
    ('FUNC_CODE', '功能号', '', ''),
    ('CHG_CONT', '修改动作', '', ''),
    ('ECIF_CUST_NO', 'ECIF客户编号', '', ''),
    ('CUST_NAME', '客户名称', '', ''),
    ('CERT_TYPE', 'CERT_TYPE', '', ''),
    ('CERT_ID', '证件号码', '', ''),
    ('DAY_UP_AMT', '全渠道限额', '', ''),
    ('CHANL_CUST_NO', '渠道客户号', '', ''),
    ('CUST_NO', '客户编号', '', ''),
    ('CHANL_NO', '渠道编号', '', ''),
    ('SIGN_STS', 'P_签约状态', '', ''),
    ('SIGN_BRAN', '签约机构编号', '', ''),
    ('MAIN_TEL_NO', '主叫号码', '', ''),
    ('DN', '手机号码', '', ''),
    ('AUTH_TYPE', '验证类型', '', ''),
    ('AUTH_NO', '授权人编号', '', ''),
    ('UKEY_NO', 'Ukey号码', '', ''),
    ('CUST_FEE_LEV', '计费类别', '', ''),
    ('CHARG_ACCT', '指定扣费账号', '', ''),
    ('CUST_MGR', '保全客户经理A', '', ''),
    ('REMARK1', '备注1', '', ''),
    ('REMARK2', '说明2', '', ''),
    ('REMARK3', '备注3', '', ''),
    ('P9_DATA_DATE', 'P9数据日期', '', ''),
    ('P9_BATCH_NUMBER', '42', '', ''),
    ('P9_DEL_FLAG', '', '', ''),
    ('P9_DEL_DATE', '42', '', ''),
    ('P9_DEL_BATCH', '42', '', ''),
    ('P9_JOB_NAME', '', '', ''),
]
