#field_en, field_cn, field_type, field_length, field_is_pk, field_is_dk, field_to_ctbase, index_describe, index_function, index_split, field_filter
table_cn = '帐户签约信息痕迹'
field_array = [
    ('FLOW_NO', '交易流水号', '', ''),
    ('ECIF_CUST_NO', 'ECIF客户编号', '', ''),
    ('FUNC_CODE', '功能号', '', ''),
    ('CHANL_CUST_NO', '渠道客户号', '', ''),
    ('CHANL_NO', '渠道编号', '', ''),
    ('SIGN_BRAN', '签约机构编号', '', ''),
    ('ACCT_NO', '会计账号', '', ''),
    ('SIGN_TYPE', '签约属性', '', ''),
    ('CCB_ACCT_FLG', '签约类别', '', ''),
    ('ORMT_NO', '联行行号', '', ''),
    ('ORMT_NAME', '联行名称', '', ''),
    ('OPEN_BRAN', '开户机构', '', ''),
    ('ACCT_NM', '帐户户名', '', ''),
    ('ACCT_TYP', '帐别', '', ''),
    ('FSCRD_FLG', '理财卡标志', '', ''),
    ('EX_SYSTEM_ID', '系统编号', '', ''),
    ('TRANS_FLAG', '是否允许开放式转账功能', '', ''),
    ('REMARK1', '备注1', '', ''),
    ('REMARK2', '说明2', '', ''),
    ('REMARK3', '备注3', '', ''),
    ('P9_DATA_DATE', 'P9数据日期', '', ''),
    ('P9_BATCH_NUMBER', '42', '', ''),
    ('P9_DEL_FLAG', '', '', ''),
    ('P9_DEL_DATE', '42', '', ''),
    ('P9_DEL_BATCH', '42', '', ''),
    ('P9_JOB_NAME', '', '', ''),
]
