#field_en, field_cn, field_type, field_length, field_is_pk, field_is_dk, field_to_ctbase, index_describe, index_function, index_split, field_filter
table_cn = '帐户签约信息流水表'
field_array = [
    ('FLOW_NO', '交易流水号', '', ''),
    ('ECIF_CUST_NO', 'ECIF客户编号', '', ''),
    ('FUNC_CODE', '功能号', '', ''),
    ('CHANL_CUST_NO', '渠道客户号', '', ''),
    ('CHANL_NO', '渠道编号', '', ''),
    ('SIGN_BRAN', '签约机构', '', ''),
    ('ACCT_NO', '帐号', '', ''),
    ('SIGN_TYPE', '签约状态', '', ''),
    ('CCB_ACCT_FLG', '签约类别', '', ''),
    ('ORMT_NO', '联行行号', '', ''),
    ('ORMT_NAME', '联行名称', '', ''),
    ('OPEN_BRAN', '开户机构', '', ''),
    ('ACCT_NM', '帐户户名', '', ''),
    ('ACCT_TYP', '帐别', '', ''),
    ('FSCRD_FLG', '理财卡标志', '', ''),
    ('EX_SYSTEM_ID', '系统编号', '', ''),
    ('TRANS_FLAG', '交易标志', '', ''),
    ('REMARK1', '说明1', '', ''),
    ('REMARK2', '说明2', '', ''),
    ('REMARK3', '备注3', '', ''),
    ('P9_SPLIT_BRANCH_CD', '按机构拆分字段', '', ''),
    ('P9_DATA_DATE', 'P9数据日期', '', ''),
    ('P9_BATCH_NUMBER', 'P9批次号', '', ''),
    ('P9_DEL_FLAG', 'P9删除标志', '', ''),
    ('P9_DEL_DATE', 'P9删除日期', '', ''),
    ('P9_DEL_BATCH', 'P9删除批次号', '', ''),
    ('P9_JOB_NAME', 'P9作业名', '', ''),
]
