#field_en, field_cn, field_type, field_length, field_is_pk, field_is_dk, field_to_ctbase, index_describe, index_function, index_split, field_filter
table_cn = '内外客户号对照信息'
field_array = [
    ('MULTI_TENANCY_ID', '多实体标识', '', ''),
    ('SRC_INF_STM_CD', '源信息系统代码', 'Y', ''),
    ('SRCSYS_CST_ID', '源系统客户编号', 'Y', 'n'),
    ('RCRD_EXPY_TMS', '记录失效时间戳', '', ''),
    ('CST_ID', '客户编号', 'Y', 'n'),
    ('RSRV_CST_ID', '备用客户编号', '', ''),
    ('CRT_INSID', '创建机构编号', '', ''),
    ('CRT_EMPID', '创建员工编号', '', ''),
    ('LAST_UDT_INSID', '最后更新机构编号', '', ''),
    ('LAST_UDT_EMPID', '最后更新员工编号', '', ''),
    ('CUR_STM_CRT_TMS', '当前系统创建时间戳', '', ''),
    ('CUR_STM_UDT_TMS', '当前系统更新时间戳', '', ''),
    ('LCL_YRMO_DAY', '本地年月日', '', ''),
    ('LCL_HR_GRD_SCND', '本地时分秒', '', ''),
    ('CRT_STM_NO', '创建系统号', '', ''),
    ('UDT_STM_NO', '更新系统号', '', ''),
    ('SRCSYS_CRT_TMS', '源系统创建时间戳', '', ''),
    ('SRCSYS_UDT_TMS', '源系统更新时间戳', '', ''),
    ('P9_START_DATE', 'P9开始日期', 'Y', ''),
    ('P9_START_BATCH', 'P9_START_BATCH', '', ''),
    ('P9_END_DATE', 'P9结束日期', 'Y', ''),
    ('P9_END_BATCH', 'P9_END_BATCH', '', ''),
    ('P9_DEL_FLAG', 'P9_DEL_FLAG', '', ''),
    ('P9_JOB_NAME', 'P9_JOB_NAME', '', ''),
]
