#field_en, field_cn, field_type, field_length, field_is_pk, field_is_dk, field_to_ctbase, index_describe, index_function, index_split, field_filter
table_cn = '个人客户基本信息（CIF）扩展表'
field_array = [
    ('CUST_NO', 'CCBS客户编号', '', ''),
    ('ACTIVE_DATE', '激活日期', '', ''),
    ('IS_ACTIVE', '激活标志', '', ''),
    ('DN', '手机号码', '', ''),
    ('IMSI', '手机IMSI号', '', ''),
    ('MOBILE_TYPE1', '手机型号', '', ''),
    ('CLASSID', '平台号', '', ''),
    ('VERSION1', '程序版本号', '', ''),
    ('MOBILE_TYPE2', '手机型号', '', ''),
    ('CLIENTID', '客户号', '', ''),
    ('BROWSER_TYPE', '浏览器类型', '', ''),
    ('VERSION2', '程序版本号', '', ''),
    ('MOBILE_TYPE3', '手机型号', '', ''),
    ('VERSION3', '程序版本号', '', ''),
    ('LAST_LOGIN', '手机登录时间', '', ''),
    ('CERT_ID', '证件号码', '', ''),
    ('CERT_EXP', '证书过期日期', '', ''),
    ('PAY_ID', '缴费流水ID', '', ''),
    ('CHANNEL', '开通渠道', '', ''),
    ('P9_START_DATE', 'P9开始日期', '', ''),
    ('P9_START_BATCH', 'P9开始批次号', '', ''),
    ('P9_END_DATE', 'P9结束日期', '', ''),
    ('P9_END_BATCH', 'P9结束批次号', '', ''),
    ('P9_DEL_FLAG', 'P9删除标志', '', ''),
    ('P9_JOB_NAME', 'P9作业名', '', ''),
]
