#field_en, field_cn, field_type, field_length, field_is_pk, field_is_dk, field_to_ctbase, index_describe, index_function, index_split, field_filter
table_cn = 'ATM交易明细档'
field_array = [
    ('CR_ATM_NO', 'ATM编号', 'Y', 'y'),
    ('CRDET_LL', '(空值)', '', ''),
    ('CR_TX_DT', '交易日期', 'Y', 'y'),
    ('CR_ATM_TX_SQ_NO', 'ATM交易序号', 'Y', ''),
    ('CRDET_DB_TIMESTAMP', '(空值)', '', ''),
    ('CR_RSV_FLG', '备用标志', '', ''),
    ('CR_CURR_COD', '币别', '', ''),
    ('CR_EC_FLG', '冲正标志', '', 'y'),
    ('CR_OPR_EC', '冲正员号', '', 'y'),
    ('CR_ENTR_DT', '记帐日期', '', ''),
    ('CR_TX_NO', '交易代号', 'Y', 'y'),
    ('CR_TX_AMT', '交易金额', 'Y', 'y'),
    ('CR_TX_LOG_NO', '交易流水号', 'Y', ''),
    ('CR_TX_TM', '交易时间', 'Y', 'y'),
    ('CR_TX_NETP_NO', '交易网点号', 'Y', 'y'),
    ('CR_CRD_NO', '卡号', 'Y', 'y'),
    ('CR_CPU_DT', '系统日期', '', ''),
    ('CR_GCRD_TX_SQ_NO', '金卡交易流水号', '', ''),
    ('CR_DRGN_CRD_TX_SQ_N', '龙卡交易流水号', '', ''),
    ('CR_CONF_FLG', '确认标志', '', ''),
    ('CR_DSCRP_COD', '摘要代码', 'Y', 'y'),
    ('CR_TRNI_SAV_NO', '转入帐号', 'Y', 'y'),
    ('CR_TRNO_SAV_NO', '转出帐号', 'Y', 'y'),
    ('CR_PSBK_SQ_NO', '笔号', '', ''),
    ('FILLER', 'FILLER', '', ''),
    ('P9_SPLIT_BRANCH_CD', '按机构拆分字段', '', ''),
    ('P9_DATA_DATE', 'P9数据日期', 'Y', ''),
    ('P9_BATCH_NUMBER', 'P9批次号', '', ''),
    ('P9_DEL_FLAG', 'P9删除标志', '', ''),
    ('P9_DEL_DATE', 'P9删除日期', '', ''),
    ('P9_DEL_BATCH', 'P9删除批次号', '', ''),
    ('P9_JOB_NAME', 'P9作业名', '', ''),
]
