#field_en, field_cn, field_type, field_length, field_is_pk, field_is_dk, field_to_ctbase, index_describe, index_function, index_split, field_filter
table_cn = '登录流水表'
field_array = [
    ('QUERY_FLOW_NO', '平台查询流水号', 'Y', ''),
    ('CHANL_NO', '渠道编号', 'Y', 'y'),
    ('CHANL_ADAP_NO', '渠道适配号', '', ''),
    ('FLAT_TRAD_DATE', '交易日期', 'Y', 'y'),
    ('BACK_TRAD_NM', '后台系统名称', '', ''),
    ('CUST_NO', 'CCBS客户编号', 'Y', 'y'),
    ('CHANL_CUST_NO', '渠道客户号', 'Y', 'y'),
    ('CUST_NM', '户名', 'Y', ''),
    ('CUST_TYP', '客户类型', '', ''),
    ('CUST_GRD', '客户级别', '', ''),
    ('SIGN_STS', '签约状态', '', ''),
    ('ACCT_NO', '帐号', 'Y', 'y'),
    ('ACCT_TYP', '帐别', 'Y', ''),
    ('ACCT_BRAN', '主账号所属机构', 'Y', ''),
    ('TRAD_NO', '平台交易码', 'Y', ''),
    ('TRAD_NM', '平台交易名称', 'Y', ''),
    ('ITCD_NO', '业务编码', 'Y', ''),
    ('FLAT_TRAD_TIME', '平台交易时间', 'Y', 'y'),
    ('FLAT_SYS_DATE', '平台系统日期', '', ''),
    ('TRAD_BRAN', '交易机构', 'Y', 'y'),
    ('SIGN_BRAN', '签约机构', '', 'y'),
    ('RETURN_CODE', '响应码', 'Y', 'y'),
    ('RETURN_MSG', '响应信息', 'Y', 'y'),
    ('TERM_INF', '终端信息', 'Y', 'y'),
    ('ADD_INF', '登录补充信息', '', ''),
    ('MON_INF', '风险监控信息', 'Y', 'y'),
    ('TRAD_STS', '成功标志', '', 'y'),
    ('P9_SPLIT_BRANCH_CD', '按机构拆分字段', '', ''),
    ('P9_DATA_DATE', 'P9数据日期', 'Y', ''),
    ('P9_BATCH_NUMBER', 'P9批次号', '', ''),
    ('P9_DEL_FLAG', '', '', ''),
    ('P9_DEL_DATE', 'P9删除日期', '', ''),
    ('P9_DEL_BATCH', 'P9删除批次号', '', ''),
    ('P9_JOB_NAME', '', '', ''),
]
