#field_en, field_cn, field_type, field_length, field_is_pk, field_is_dk, field_to_ctbase, index_describe, index_function, index_split, field_filter
table_cn = '超网交易痕迹'
field_array = [
    ('FLOW_NO', '交易流水号', '', ''),
    ('CHANL_NO', '渠道编号', '', ''),
    ('CHANL_ADAP_NO', '渠道适配号', '', ''),
    ('FLAT_TRAD_DATE', '交易日期', '', ''),
    ('FLAT_TRAD_TIME', '平台交易时间', '', ''),
    ('FLAT_SYS_DATE', '平台系统日期', '', ''),
    ('CHANL_DATE', '渠道流水周期', '', ''),
    ('CHANL_FLOW_NO', '流水号', '', ''),
    ('BACK_TRAD_NM', '后台系统名称', '', ''),
    ('BACK_TRAD_DATE', '后台交易日期', '', ''),
    ('BACK_FLOW_NO', '后台流水号', '', ''),
    ('CUST_NO', '客户编号', '', ''),
    ('CHANL_CUST_NO', '渠道客户号', '', ''),
    ('CUST_NM', '户名', '', ''),
    ('CUST_TYP', '客户类型', '', ''),
    ('CUST_GRD', '客户级别', '', ''),
    ('TRAD_NO', '平台交易码', '', ''),
    ('ITCD_NO', '业务编码', '', ''),
    ('AMT1', '金额1', '', ''),
    ('AMT2', '金额2', '', ''),
    ('AMT3', '金额3', '', ''),
    ('SVC', '手续费', '', ''),
    ('CURR', '币种', '', ''),
    ('ACCT_NO', '会计账号', '', ''),
    ('ACCT_TYPE', '账户类型1 活期；2 定期；3 贷款', '', ''),
    ('ACCT_NAME', '账户名称', '', ''),
    ('ASS_ACCT_NO', '交易辅账号', '', ''),
    ('ASS_ACCT_TYPE', '交易辅账号类型', '', ''),
    ('ASS_ACCT_NAME', '转入账户名称', '', ''),
    ('TRAD_BRAN', '交易机构', '', ''),
    ('ACCT_BRAN', '主账号所属机构', '', ''),
    ('ASS_ACCT_BRAN', '辅账号所属机构', '', ''),
    ('RETURN_CODE', '响应码', '', ''),
    ('RETURN_MSG', '响应信息', '', ''),
    ('TRAD_TLR', '交易柜员', '', ''),
    ('AUTH_TLR', '授权柜员', '', ''),
    ('TERM_INF', '终端信息', '', ''),
    ('TOT_FLG', '日交易累计标志', '', ''),
    ('ENT_OPT_NO', '发送方操作员编号', '', ''),
    ('CUST_MGR', '保全客户经理A', '', ''),
    ('SIGN_BRAN', '签约机构编号', '', ''),
    ('TRAD_STS', '成功标志', '', ''),
    ('P9_DATA_DATE', 'P9数据日期', '', ''),
    ('P9_BATCH_NUMBER', '42', '', ''),
    ('P9_DEL_FLAG', '', '', ''),
    ('P9_DEL_DATE', '42', '', ''),
    ('P9_DEL_BATCH', '42', '', ''),
    ('P9_JOB_NAME', '', '', ''),
]
