#field_en, field_cn, field_type, field_length, field_is_pk, field_is_dk, field_to_ctbase, index_describe, index_function, index_split, field_filter
table_cn = '财付通交易流水表'
field_array = [
    ('SYS_DATE', '系统时间', '', ''),
    ('SYS_TIME', '当前系统日期', '', ''),
    ('SYS_CODE', 'SYS_CODE', '', ''),
    ('TX_DATE', 'TX_DATE', '', ''),
    ('TX_TIME', 'TX_TIME', '', ''),
    ('CHANNEL_ID', '组件编号', '', ''),
    ('MERCHANT_ID', 'MERCHANT_ID', '', ''),
    ('TERM_NO', 'TERM_NO', '', ''),
    ('SEQ_ID', '序列编号', '', ''),
    ('SEQ_NO', '顺序号', '', ''),
    ('OTH_SEQ', 'OTH_SEQ', '', ''),
    ('ORG_SEQ', 'ORG_SEQ', '', ''),
    ('HOST_SEQ', 'HOST_SEQ', '', ''),
    ('HOST_TXCODE', 'HOST_TXCODE', '', ''),
    ('HOST_DATE', 'HOST_DATE', '', ''),
    ('HOST_TIME', 'HOST_TIME', '', ''),
    ('ACCOUNT_NO', '个贷帐号', '', ''),
    ('TX_AMT', '交易金额', '', ''),
    ('TX_FEE', 'TX_FEE', '', ''),
    ('BACK_BILL', 'BACK_BILL', '', ''),
    ('TX_FLAG', '交易状态', '', ''),
    ('ORDER_NO', '排序号', '', ''),
    ('AUTH_NO', '授权人编号', '', ''),
    ('TIM_NUM', 'TIM_NUM', '', ''),
    ('OTH_REQ', 'OTH_REQ', '', ''),
    ('HOST_REQ', 'HOST_REQ', '', ''),
    ('HOST_MESSAGE', 'HOST_MESSAGE', '', ''),
    ('RET_CODE', '返回码', '', ''),
    ('RET_MSG', '返回信息', '', ''),
    ('TX_STAT', 'TX_STAT', '', ''),
    ('MEMO1', '备注3', '', ''),
    ('MEMO2', '备注2', '', ''),
    ('MEMO3', '备注3', '', ''),
    ('ETL_LOAD_DT', 'ETL_LOAD_DT', '', ''),
    ('P9_SPLIT_BRANCH_CD', 'P9_SPLIT_BRANCH_CD', '', ''),
    ('P9_DATA_DATE', 'P9_DATA_DATE', '', ''),
    ('P9_BATCH_NUMBER', 'P9_BATCH_NUMBER', '', ''),
    ('P9_DEL_FLAG', 'P9_DEL_FLAG', '', ''),
    ('P9_DEL_DATE', 'P9_DEL_DATE', '', ''),
    ('P9_DEL_BATCH', 'P9_DEL_BATCH', '', ''),
    ('P9_JOB_NAME', 'P9_JOB_NAME', '', ''),
]
