#field_en, field_cn, field_type, field_length, field_is_pk, field_is_dk, field_to_ctbase, index_describe, index_function, index_split, field_filter
table_cn = '挂起交易明细表'
field_array = [
    ('FLOW_NO', '交易流水号', '', ''),
    ('CONFIRM_FLOW_NO', '', '', ''),
    ('BLACK_ID', '', '', ''),
    ('CUST_NO', 'CCBS客户编号', '', ''),
    ('CHANL_NO', '渠道编号', '', ''),
    ('CUST_TYPE', '客户类型', '', ''),
    ('CHANL_TRAD_NO', '交易码', '', ''),
    ('CHANL_ADAP', '', '', ''),
    ('ACCT_NO', '帐号', '', ''),
    ('TRAD_DATE', '交易日期', '', ''),
    ('TRAD_TIME', '交易时间', '', ''),
    ('AMT1', '金额1', '', ''),
    ('TRAD_BRAN', '交易机构', '', ''),
    ('CONFIRM_SERVICE', '', '', ''),
    ('OTHER_SERVICE', '', '', ''),
    ('RULE_ID', '规则编号', '', ''),
    ('RULE_DESC', '规则描述', '', ''),
    ('OPT_ID', '选项编号', '', ''),
    ('PROC_DATE', '处理日期', '', ''),
    ('PROC_TIME', '', '', ''),
    ('AP_STATUS', '', '', ''),
    ('STATUS', '状态', '', ''),
    ('DEAL_FLAG', '优化前后标志', '', ''),
    ('P9_DATA_DATE', 'P9数据日期', '', ''),
    ('P9_BATCH_NUMBER', 'P9批次号', '', ''),
    ('P9_DEL_FLAG', '', '', ''),
    ('P9_DEL_DATE', 'P9删除日期', '', ''),
    ('P9_DEL_BATCH', 'P9删除批次号', '', ''),
    ('P9_JOB_NAME', '', '', ''),
]
