#field_en, field_cn, field_type, field_length, field_is_pk, field_is_dk, field_to_ctbase, index_describe, index_function, index_split, field_filter
table_cn = '地址信息'
field_array = [
    ('EXTERNALBUSINESSRE', '客户编号', '', ''),
    ('SOURCECREATEDTIMES', '创建时间', '', ''),
    ('SOURCEUPDATEDTIMES', '更新时间', '', ''),
    ('CONTACTTYPE', '', '', ''),
    ('CR_HOME_PHONE', '家庭电话', '', ''),
    ('CR_CO_HOME_PHONE', '手机号', '', ''),
    ('CR_OFFICE_PHONE', '公司电话', '', ''),
    ('CR_CO_OFFICE_PHONE', '', '', ''),
    ('CR_ADDR_1', '地址行1', '', ''),
    ('CR_ADDR_2', '地址行2', '', ''),
    ('CR_CITY', '地址行3', '', ''),
    ('CR_ADDL_ADDR_1', '其它地址1', '', ''),
    ('CR_ADDL_ADDR_2', '其它地址2', '', ''),
    ('CR_ADDL_ADDR_3', '其它地址3', '', ''),
    ('EMAIL', '邮件', '', ''),
    ('POSTALCODE', '邮编', '', ''),
    ('ROLETYPE', '类型代码', '', ''),
    ('CONTDESC', '', '', ''),
    ('AREACDE', '地区代码', '', ''),
    ('EXTN', '展期', '', ''),
    ('CREATESYSTEMID', '创建时间', '', ''),
    ('UPDATESYSTEMID', '更新时间', '', ''),
    ('ROLEPLAYER', 'rolePlayer', '', ''),
    ('CR_ORG_NBR', '', '', ''),
    ('P9_START_DATE', 'P9开始日期', '', ''),
    ('P9_START_BATCH', '', '', ''),
    ('P9_END_DATE', 'P9结束日期', '', ''),
    ('P9_END_BATCH', '', '', ''),
    ('P9_DEL_FLAG', '', '', ''),
    ('P9_JOB_NAME', '', '', ''),
]
