#field_en, field_cn, field_type, field_length, field_is_pk, field_is_dk, field_to_ctbase, index_describe, index_function, index_split, field_filter
table_cn = '排队机流水'
field_array = [
    ('CCBINS_ID             ', '机构代码', 'Y', ''),
    ('CST_OFRNUM_DT         ', '', 'Y', ''),
    ('CST_OFRNUM_TM         ', '', 'Y', ''),
    ('TLR_CLNUM_TM          ', '', 'Y', ''),
    ('TLR_SVC_EDTM          ', '', 'Y', ''),
    ('CST_ASS_TM            ', '', 'Y', ''),
    ('BO_QU_BILLNO          ', '', 'Y', ''),
    ('SRCSYS_AR_ID          ', '', 'Y', ''),
    ('BO_QU_OFRNUM_BSN_CTCD ', '', 'Y', ''),
    ('LVL2_BSN_CTCD         ', '', 'Y', ''),
    ('CST_QU_STCD           ', '', 'Y', ''),
    ('CST_TPCD              ', '', 'Y', ''),
    ('MSG_EMAIL_PRTY        ', '', 'Y', ''),
    ('CST_SSF_CD            ', '', 'Y', ''),
    ('BO_CNTER_ID           ', '', 'Y', ''),
    ('ORIG_STM_USR_ID       ', '', 'Y', ''),
    ('REQ_CCB_PDRCMM_IND    ', '', 'Y', ''),
    ('CMPN_CHNL_CD          ', '', 'Y', ''),
    ('RCMCST_MGR_ID         ', '', 'Y', ''),
    ('RSRV_FLD1_INF         ', '', 'Y', ''),
    ('P9_DATA_DATE', 'P9数据日期', 'Y', ''),
    ('P9_BATCH_NUMBER', 'P9批次号', '', ''),
    ('P9_DEL_FLAG', 'P9删除标志', '', ''),
    ('P9_DEL_DATE', 'P9删除日期', '', ''),
    ('P9_DEL_BATCH', 'P9删除批次号', '', ''),
    ('P9_JOB_NAME', 'P9作业名', '', ''),
]
