#field_en, field_cn, field_type, field_length, field_is_pk, field_is_dk, field_to_ctbase, index_describe, index_function, index_split, field_filter
table_cn = '员工'
field_array = [
    ('CCB_EMPID', '建行员工编号', 'Y', ''),
    ('GND_CD', '性别代码', 'Y', ''),
    ('USR_NM', '用户姓名', 'Y', ''),
    ('HMNRSC_EMPID', '人力资源员工编号', 'Y', ''),
    ('EMPE_ID_LAND_NM', '员工识别登录名', 'Y', ''),
    ('CRDT_TPCD', '证件类型代码', 'Y', ''),
    ('CRDT_NO', '证件号码', 'Y', ''),
    ('USR_TPCD', '用户类型代码', '', ''),
    ('USR_STCD', '用户状态代码', 'Y', ''),
    ('TELCTCMOD_WRK_NO', '电话联系方式办公号码', 'Y', ''),
    ('TELCTCMOD_MBLPH_NO', '电话联系方式手机号码', 'Y', ''),
    ('TELCTCMOD_FAX_NO', '电话联系方式传真号码', '', ''),
    ('TELCTCMOD_RSRV_NO', '电话联系方式备用号码', '', ''),
    ('EMAIL_ADR_CNTNT', '电子邮件地址内容', '', ''),
    ('IDV_NM_SURNM', '个人名称姓氏', 'Y', ''),
    ('IDV_NM_NM', '个人名称名', 'Y', ''),
    ('ZIPECD', '邮政编码', '', ''),
    ('DTL_ADR', '详细地址', 'Y', ''),
    ('BLNG_INSID', '所属机构编号', 'Y', ''),
    ('WRK_UNIT_NM', '工作单位名称', '', ''),
    ('EXT_USR_POST', '外部用户职务', '', ''),
    ('EDDGR_CD', '学历代码', '', ''),
    ('DGR_CD', '学位代码', '', ''),
    ('GRDT_SCH_CD', '毕业学校代码', '', ''),
    ('SCH_CHAR_CD', '学校性质代码', '', ''),
    ('MJR_CD', '所学专业代码', '', ''),
    ('STDY_FORM_CD', '学习形式代码', '', ''),
    ('USR_NM_CPA_FULLNM', '用户姓名拼音全称', '', ''),
    ('EMPE_PST_LOCK_STCD', '员工岗位锁定状态代码', '', ''),
    ('EFDT_TM', '生效日期时间', 'Y', ''),
    ('CRT_STM_MGT_OPR_ID', '创建系统管理操作员编号', '', ''),
    ('LAST_UDT_DT_TM', '最后更新日期时间', '', ''),
    ('OTHR_PROF_NM', '其他专业名称', '', ''),
    ('P9_START_DATE', 'P9开始日期', 'Y', ''),
    ('P9_START_BATCH', '', '', ''),
    ('P9_END_DATE', 'P9结束日期', 'Y', ''),
    ('P9_END_BATCH', '', '', ''),
    ('P9_DEL_FLAG', '', '', ''),
    ('P9_JOB_NAME', '', '', ''),
    ('EMPE_PIC_FILE_INDX_NO', '员工照片文件索引号', '', ''),
    ('BRTH_DT', '出生日期', '', ''),
    ('EMGR_CTC_MOD_CNTNT', '紧急联系方式内容', '', ''),
    ('GRDT_DT', '毕业日期', '', ''),
]
