#field_en, field_cn, field_type, field_length, field_is_pk, field_is_dk, field_to_ctbase, index_describe, index_function, index_split, field_filter
table_cn = '登录痕迹'
field_array = [
    ('PLAT_FLOW_NO', '电子渠道平台流水号', '', ''),
    ('CHNL_TPCD', '渠道类型代码', '', ''),
    ('CHNL_ADAP_ID', '渠道适配号', '', ''),
    ('PLAT_TXN_DATE', '平台交易日期', '', ''),
    ('BACK_SYS_NM', '后台系统名称', '', ''),
    ('EBNK_CST_PLTFRM_ID', '电子银行客户平台编号', '', ''),
    ('CHNL_CUST_NO', '渠道客户号', '', ''),
    ('CST_NM', '客户名称', '', ''),
    ('RSRV_TPCD', '备用类型代码', '', ''),
    ('EBNK_LVL_ECD', 'EBNK_LVL_ECD', '', ''),
    ('EBNK_SIGN_ST', '电子银行签约状态', '', ''),
    ('ACCNO', '账号', '', ''),
    ('ACC_TPCD', '账户类型代码', '', ''),
    ('HDL_INSID', '经办机构编号', '', ''),
    ('PLAT_TXN_CODE', '电子渠道平台交易码', '', ''),
    ('TXN_DSC', '交易描述', '', ''),
    ('RSRV_2', '备用二', '', ''),
    ('PLAT_TXN_TIME', '平台交易时间', '', ''),
    ('PLAT_SYS_DATE', '平台系统日期', '', ''),
    ('TXN_INSID', '交易机构编号', '', ''),
    ('SIGN_INSID', '签约机构编号', '', ''),
    ('SYS_RESP_CODE', '响应码', '', ''),
    ('SYS_RESP_DESC', '服务响应描述', '', ''),
    ('TERM_INF', '终端信息', '', ''),
    ('IP_ADD', 'IP地址', '', ''),
    ('RSRV_1', '备用一', '', ''),
    ('ECHNL_TXN_STCD', '电子渠道交易状态代码', '', ''),
    ('P9_DATA_DATE', 'P9数据日期', '', ''),
    ('P9_BATCH_NUMBER', '42', '', ''),
    ('P9_DEL_FLAG', '', '', ''),
    ('P9_DEL_DATE', '42', '', ''),
    ('P9_DEL_BATCH', '42', '', ''),
    ('P9_JOB_NAME', '', '', ''),
]
