#field_en, field_cn, field_type, field_length, field_is_pk, field_is_dk, field_to_ctbase, index_describe, index_function, index_split, field_filter
table_cn = '建行机构和位置关系'
field_array = [
    ('CTY_CD', '国家代码', '', ''),
    ('DTL_ADR', '详细地址', '', ''),
    ('ZIPECD', '邮政编码', '', ''),
    ('CCBINS_ID', '建行机构编号', '', ''),
    ('LO_ID', '位置编号', '', ''),
    ('CCBINS_AND_LO_RETPCD', '建行机构和位置关系类型代码', '', ''),
    ('CCBINSANDLORELST_TM', '建行机构和位置关系开始时间', '', ''),
    ('CCBINSANDLORELED_TM', '建行机构和位置关系结束时间', '', ''),
    ('CCBINSANDLORELMDF_DSC', '建行机构和位置关系变更原因描述', '', ''),
    ('GERG_TPCD', '地理区域类型代码', '', ''),
    ('GERG_DSC', '地理区域描述', '', ''),
    ('RSK_CTY_IND', '风险国家标志', '', ''),
    ('PROV_ATNMSRGON_CD', '省自治区代码', '', ''),
    ('PROV_ATNMSRGON_TPCD', '省自治区类型代码', '', ''),
    ('URBN_ATNMSDSTC_CD', '城市自治州代码', '', ''),
    ('URBN_ATNMSDSTC_TPCD', '城市自治州类型代码', '', ''),
    ('CNTYANDDSTC_CD', '区县代码', '', ''),
    ('CNTYANDDSTC_TPCD', '区县类型代码', '', ''),
    ('LGT', '经度', '', ''),
    ('LTT', '纬度', '', ''),
    ('GERG_SPTL_CORD_DSC', '地理区域空间坐标描述', '', ''),
    ('FLOOR_NUM', '楼层数', '', ''),
    ('ROOM_NO', '具体房号', '', ''),
    ('RSDNC_COMM_NM', '居住小区名称', '', ''),
    ('BDNO', '楼号', '', ''),
    ('STR_NM', '街道名称', '', ''),
    ('UNIT_NO', '单元号', '', ''),
    ('BLD_NM', '建筑名称', '', ''),
    ('MLBX_NO', '信箱号', '', ''),
    ('LAST_UDT_DT_TM', '最后更新日期时间', '', ''),
    ('P9_START_DATE', 'P9开始日期', '', ''),
    ('P9_START_BATCH', 'P9_START_BATCH', '', ''),
    ('P9_END_DATE', 'P9结束日期', '', ''),
    ('P9_END_BATCH', 'P9_END_BATCH', '', ''),
    ('P9_DEL_FLAG', 'P9_DEL_FLAG', '', ''),
    ('P9_JOB_NAME', 'P9_JOB_NAME', '', ''),
]
