#field_en, field_cn, field_type, field_length, field_is_pk, field_is_dk, field_to_ctbase, index_describe, index_function, index_split, field_filter
table_cn = '活期存款明细档.个人'
field_array = [
    ('SA_ACCT_NO', '帐号', 'Y', 'y'),
    ('SATXN_LL', '（空值）', '', ''),
    ('SA_DDP_ACCT_NO_DET_N', '活存帐户明细号', 'Y', 'y'),
    ('SATXN_DB_TIMESTAMP', '（空值）', '', ''),
    ('SA_CURR_COD', '币别', '', ''),
    ('SA_OPR_NO', '操作员号', 'Y', 'y'),
    ('SA_CURR_IDEN', '钞汇鉴别', '', ''),
    ('SA_EC_FLG', '冲正标志', '', 'y'),
    ('SA_EC_DET_NO', '冲正明细号', '', 'y'),
    ('SA_CR_AMT', '贷方发生额', '', 'y'),
    ('SA_DDP_ACCT_BAL', '活存帐户余额', 'Y', 'y'),
    ('SA_TX_AMT', '交易金额', 'Y', 'y'),
    ('SA_TX_CRD_NO', '交易卡号', 'Y', 'y'),
    ('SA_TX_TYP', '交易类别', 'Y', 'y'),
    ('SA_TX_LOG_NO', '交易流水号', 'Y', 'y'),
    ('SA_DR_AMT', '借方发生额', '', 'y'),
    ('SA_DOC_NO', '凭证号码', '', ''),
    ('SA_DOC_TYP', '凭证种类', '', ''),
    ('SA_VAL_DT', '起息日', '', ''),
    ('SA_SVC', '手续费', '', 'y'),
    ('SA_AUTH_NO', '授权号', '', ''),
    ('SA_CUST_DOCAG_STNO', '商户交单套号', '', ''),
    ('SA_OPUN_COD', '营业单位代码', 'Y', 'y'),
    ('SA_DSCRP_COD', '摘要代码', 'Y', 'y'),
    ('SA_RMRK', '备注', 'Y', 'y'),
    ('SA_TX_TM', '交易时间', 'Y', 'y'),
    ('SA_TX_DT', '交易日期', 'Y', 'y'),
    ('SA_SYS_DT', '系统日期', '', ''),
    ('SA_DDP_PDT', '活存积数', '', ''),
    ('SA_APP_TX_CODE', '交易代码', 'Y', 'y'),
    ('SA_EXT_FLG', 'ETX档标志', 'Y', 'y'),
    ('SA_OTX_FLG', '境外消费明细扩展标志', 'Y', 'y'),
    ('FILLER', 'FILLER', '', ''),
    ('SA_RMRK_1', '备注1', '', ''),
    ('SA_OP_CUST_NAME', '对方户名', '', ''),
    ('P9_SPLIT_BRANCH_CD', '按机构拆分字段', '', ''),
    ('P9_DATA_DATE', 'P9数据日期', 'Y', ''),
    ('P9_BATCH_NUMBER', 'P9批次号', '', ''),
    ('P9_DEL_FLAG', 'P9删除标志', '', ''),
    ('P9_DEL_DATE', 'P9删除日期', '', ''),
    ('P9_DEL_BATCH', 'P9删除批次号', '', ''),
    ('P9_JOB_NAME', 'P9作业名', '', ''),
]
