#field_en, field_cn, field_type, field_length, field_is_pk, field_is_dk, field_to_ctbase, index_describe, index_function, index_split, field_filter
table_cn = '查询交易流水'
field_array = [
    ('QUERY_FLOW_NO', '平台查询流水号', 'Y', ''),
    ('CHANL_NO', '渠道编号', 'Y', ''),
    ('CHANL_ADAP_NO', '渠道适配号', '', ''),
    ('FLAT_TRAD_DATE', '交易日期', 'Y', ''),
    ('CHANL_DATE', '渠道流水周期', '', ''),
    ('CHANL_FLOW_NO', '流水号', '', ''),
    ('BACK_TRAD_NM', '后台系统名称', '', ''),
    ('BACK_TRAD_DATE', '后台交易日期', '', ''),
    ('BACK_FLOW_NO', '后台流水号', '', ''),
    ('CUST_NO', 'CCBS客户编号', 'Y', ''),
    ('CHANL_CUST_NO', '渠道客户号', 'Y', ''),
    ('CUST_NM', '户名', 'Y', ''),
    ('CUST_TYP', '客户类型', '', ''),
    ('CUST_GRD', '客户级别', '', ''),
    ('ACCT_NO', '帐号', 'Y', ''),
    ('ACCT_TYP', '帐别', 'Y', ''),
    ('ACCT_BRAN', '主账号所属机构', 'Y', ''),
    ('TRAD_NO', '平台交易码', 'Y', ''),
    ('TRAD_NM', '平台交易名称', 'Y', ''),
    ('ITCD_NO', '业务编码', 'Y', ''),
    ('FLAT_TRAD_TIME', '平台交易时间', 'Y', ''),
    ('FLAT_SYS_DATE', '平台系统日期', '', ''),
    ('TRAD_BRAN', '交易机构', '', ''),
    ('SIGN_BRAN', '签约机构', '', ''),
    ('RETURN_CODE', '响应码', 'Y', ''),
    ('RETURN_MSG', '响应信息', 'Y', ''),
    ('TRAD_TLR', '交易柜员', 'Y', ''),
    ('AUTH_TLR', '授权柜员', '', ''),
    ('TERM_INF', '终端信息', 'Y', ''),
    ('TRAD_STS', '成功标志', '', ''),
    ('P9_DATA_DATE', 'P9数据日期', 'Y', ''),
    ('P9_BATCH_NUMBER', 'P9批次号', '', ''),
    ('P9_DEL_FLAG', '', '', ''),
    ('P9_DEL_DATE', 'P9删除日期', '', ''),
    ('P9_DEL_BATCH', 'P9删除批次号', '', ''),
    ('P9_JOB_NAME', '', '', ''),
]
