#field_en, field_cn, field_type, field_length, field_is_pk, field_is_dk, field_to_ctbase, index_describe, index_function, index_split, field_filter
table_cn = '签约主流水表'
field_array = [
    ('FLOW_NO', '交易流水号', 'Y', ''),
    ('CHANL_FLOW_NO', '流水号', 'Y', ''),
    ('ECIF_FLOW_NO', 'ecif流水号', 'Y', ''),
    ('ECIF_CUST_NO', 'ECIF客户编号', 'Y', ''),
    ('CUST_NO', 'CCBS客户编号', 'Y', ''),
    ('CHANL_CUST_NO', '渠道客户号', 'Y', ''),
    ('CERT_TYP', '证件类型', 'Y', ''),
    ('CERT_ID', '证件号码', 'Y', ''),
    ('CUST_NM', '户名', 'Y', ''),
    ('CHANL_TRAD_NO', '交易码', 'Y', ''),
    ('CHANL_NO', '渠道编号', 'Y', ''),
    ('SIGN_APPR', '签约途径', 'Y', ''),
    ('SIGN_BRAN', '签约机构', 'Y', ''),
    ('SIGN_TLR', '开通签约服务柜员', 'Y', ''),
    ('SIGN_DATE', '签约日期', 'Y', ''),
    ('SIGN_TIME', '交易时间', 'Y', ''),
    ('TERM_INF', '终端信息', 'Y', ''),
    ('TRAD_STS', '成功标志', 'Y', ''),
    ('RETURN_COD', '响应码', 'Y', ''),
    ('RETURN_MSG', '响应信息', 'Y', ''),
    ('REMARK1', '说明1', 'Y', ''),
    ('REMARK2', '说明2', 'Y', ''),
    ('REMARK3', '备注3', 'Y', ''),
    ('P9_SPLIT_BRANCH_CD', '按机构拆分字段', '', ''),
    ('P9_DATA_DATE', 'P9数据日期', 'Y', ''),
    ('P9_BATCH_NUMBER', 'P9批次号', '', ''),
    ('P9_DEL_FLAG', 'P9删除标志', '', ''),
    ('P9_DEL_DATE', 'P9删除日期', '', ''),
    ('P9_DEL_BATCH', 'P9删除批次号', '', ''),
    ('P9_JOB_NAME', 'P9作业名', '', ''),
]
