use sor;

-- Hive建表脚本
-- 银行卡主档: TODDC_CRCRDCRD_H

-- 外部表
DROP TABLE IF EXISTS EXT_TODDC_CRCRDCRD_H;

CREATE EXTERNAL TABLE IF NOT EXISTS EXT_TODDC_CRCRDCRD_H(
   -- (空值)
   CRCRD_LL                       string,
   -- 卡号
   CR_CRD_NO                      string,
   -- (空值)
   CRCRD_DB_TIMESTAMP             string,
   -- 备用标志1;员工标志
   CR_RSV_FLG_1                   string,
   -- 备用标志2;金卡标志
   CR_RSV_FLG_2                   string,
   -- 备用标志3;[信用/储蓄]卡标志
   CR_RSV_FLG_3                   string,
   -- 备用标志4;带折标志
   CR_RSV_FLG_4                   string,
   -- 备用标志5;综合理财标志
   CR_RSV_FLG_5                   string,
   -- 备用标志6;发卡标志
   CR_RSV_FLG_6                   string,
   -- 备用标志7;级别标志
   CR_RSV_FLG_7                   string,
   -- 备用标志8
   CR_RSV_FLG_8                   string,
   -- 彩照标志
   R_COLOR_PHOTO_FLAG             string,
   -- 单位卡标志
   CR_UNIT_CRD_FLG                string,
   -- 单位客户编号
   CR_UNIT_CUST_NO                string,
   -- 当日ATM取款次数
   CRNT_DT_ATM_DRW_TM             string,
   -- 当日ATM取款金额
   RNT_DT_ATM_DRW_AMT             string,
   -- 挂失日期
   CR_DL_DT                       string,
   -- 挂失状态
   CR_DL_STS                      string,
   -- 借贷别
   CR_DR_CR_COD                   string,
   -- 卡种代码
   CR_CRD_TYP_COD                 string,
   -- 卡状态
   CR_CRD_STS                     string,
   -- 客户编号
   CR_CUST_NO                     string,
   -- 联名代码
   CR_JONT_COD                    string,
   -- 注销状态一;银行主动注销
   CR_CNCL_STS1                   string,
   -- 注销状态二;主卡注销附属卡
   CR_CNCL_STS2                   string,
   -- 注销状态三;单位注销单位卡
   CR_CNCL_STS3                   string,
   -- 注销状态四;担保人撤保
   CR_CNCL_STS4                   string,
   -- 注销状态五;主卡申请注销
   CR_CNCL_STS5                   string,
   -- 注销状态六;系统自动止付
   CR_CNCL_STS6                   string,
   -- 认同代码
   CR_AGRE_COD                    string,
   -- 事故序号
   CR_ACCD_SQ_NO                  string,
   -- 收费标志1
   CR_COLC_FLG1                   string,
   -- 收费标志2
   CR_COLC_FLG2                   string,
   -- 收费标志3
   CR_COLC_FLG3                   string,
   -- 收费标志4
   CR_COLC_FLG4                   string,
   -- 收费标志5
   CR_COLC_FLG5                   string,
   -- 收费标志6
   CR_COLC_FLG6                   string,
   -- 收费标志7;临时额度标志
   CR_COLC_FLG7                   string,
   -- 收费标志8;银联标志
   CR_COLC_FLG8                   string,
   -- 信用等级
   CR_CRDG                        string,
   -- 延期状态
   CR_DELAY_STS                   string,
   -- 年费收取比例
   CR_ANFE_CHG_PCT                string,
   -- 年费已扣收金额
   CR_ANFE_REV_AMT                string,
   -- 年费收取年份
   CR_ANFE_YEAR                   string,
   -- 年费未扣收月数
   ANFE_UNPAY_MONTHS              string,
   -- CVV2
   CR_CVV2                        string,
   -- 备注
   CR_FILLER_CRD                  string,
   -- 营业单位代码
   CR_OPUN_COD                    string,
   -- 有效期限
   CR_EXPD_DT                     string,
   -- 制卡状态
   CR_CRDMD_STS                   string,
   -- 主附卡标志
   CR_MNSUB_DRP                   string,
   -- 主卡卡号
   CR_PCRD_NO                     string,
   -- 注销日期
   CR_CNCLC_DT                    string,
   -- 注销状态
   CR_CNCL_STS                    string,
   -- 专用代码
   CR_SPUS_COD                    string,
   -- 版本号
   CR_VRSN_NO                     string,
   -- 卡片工本费收取比例
   R_CRD_COST_REV_RTO             string,
   -- 代发工资标志
   CR_AGENT_PAY_FLG               string,
   -- ATM上次交易日期
   CR_ATM_LTM_TX_DT               string,
   -- 客户申请编号
   CR_CUST_APLY_NO                string,
   -- 更改日期
   CR_CHG_GRNTR_DT                string,
   -- 开卡日期
   CR_OPCR_DATE                   string,
   -- 当日ATM转帐次数
   CRNT_DT_ATM_TRN_TM             string,
   -- 当日ATM转帐金额
   RNT_DT_ATM_TRN_AMT             string,
   -- 当日他行转帐次数
   CRNT_DT_TB_TRN_TM              string,
   -- 当日他行转帐金额
   CRNT_DT_TB_TRN_AMT             string,
   -- 止付日期
   CR_STPMT_DATE                  string,
   -- 发卡机构号
   CR_APP_NO                      string,
   -- 当日外币ATM取款次数
   CRNT_FX_ATM_DRW_TM             string,
   -- 当日外币ATM取款金额
   RNT_FX_AMT_DRW_AMT             string,
   -- 密码
   CR_PSWD                        string,
   -- 密码次数
   CR_PSWD_CNT                    string,
   -- 二磁道
   CR_SEC_MT_CON                  string,
   -- 二磁道校验次数
   CR_SEC_MT_CON_CNT              string,
   -- POS密码检查标志
   CR_POS_CHK_FLG                 string,
   -- IC卡主帐户
   CR_IC_PCRD_NO                  string,
   -- 换卡日期
   CR_CRD_CHG_DT                  string,
   -- IC卡数量
   CR_IC_CNT                      string,
   -- 换卡机构号
   CR_CHG_OPUN_COD                string,
   -- 失效日期出错次数
   HK_INVALI_DT_TIMES             string,
   -- #FILLER
   FILLER                         string,
   -- 按机构拆分字段
   P9_SPLIT_BRANCH_CD             string,
   -- P9开始日期
   P9_START_DATE                  string,
   -- P9开始批次号
   P9_START_BATCH                 string,
   -- P9结束日期
   P9_END_DATE                    string,
   -- P9结束批次号
   P9_END_BATCH                   string,
   -- P9删除标志
   P9_DEL_FLAG                    string,
   -- P9作业名
   P9_JOB_NAME                    string
)
PARTITIONED BY (LOAD_DATE string)
STORED AS TEXTFILE;

-- ORC内部表，节约存储空间
DROP TABLE IF EXISTS INN_TODDC_CRCRDCRD_H;

CREATE TABLE IF NOT EXISTS INN_TODDC_CRCRDCRD_H(
   -- (空值)
   CRCRD_LL                       string,
   -- 卡号
   CR_CRD_NO                      string,
   -- (空值)
   CRCRD_DB_TIMESTAMP             string,
   -- 备用标志1;员工标志
   CR_RSV_FLG_1                   string,
   -- 备用标志2;金卡标志
   CR_RSV_FLG_2                   string,
   -- 备用标志3;[信用/储蓄]卡标志
   CR_RSV_FLG_3                   string,
   -- 备用标志4;带折标志
   CR_RSV_FLG_4                   string,
   -- 备用标志5;综合理财标志
   CR_RSV_FLG_5                   string,
   -- 备用标志6;发卡标志
   CR_RSV_FLG_6                   string,
   -- 备用标志7;级别标志
   CR_RSV_FLG_7                   string,
   -- 备用标志8
   CR_RSV_FLG_8                   string,
   -- 彩照标志
   R_COLOR_PHOTO_FLAG             string,
   -- 单位卡标志
   CR_UNIT_CRD_FLG                string,
   -- 单位客户编号
   CR_UNIT_CUST_NO                string,
   -- 当日ATM取款次数
   CRNT_DT_ATM_DRW_TM             string,
   -- 当日ATM取款金额
   RNT_DT_ATM_DRW_AMT             string,
   -- 挂失日期
   CR_DL_DT                       string,
   -- 挂失状态
   CR_DL_STS                      string,
   -- 借贷别
   CR_DR_CR_COD                   string,
   -- 卡种代码
   CR_CRD_TYP_COD                 string,
   -- 卡状态
   CR_CRD_STS                     string,
   -- 客户编号
   CR_CUST_NO                     string,
   -- 联名代码
   CR_JONT_COD                    string,
   -- 注销状态一;银行主动注销
   CR_CNCL_STS1                   string,
   -- 注销状态二;主卡注销附属卡
   CR_CNCL_STS2                   string,
   -- 注销状态三;单位注销单位卡
   CR_CNCL_STS3                   string,
   -- 注销状态四;担保人撤保
   CR_CNCL_STS4                   string,
   -- 注销状态五;主卡申请注销
   CR_CNCL_STS5                   string,
   -- 注销状态六;系统自动止付
   CR_CNCL_STS6                   string,
   -- 认同代码
   CR_AGRE_COD                    string,
   -- 事故序号
   CR_ACCD_SQ_NO                  string,
   -- 收费标志1
   CR_COLC_FLG1                   string,
   -- 收费标志2
   CR_COLC_FLG2                   string,
   -- 收费标志3
   CR_COLC_FLG3                   string,
   -- 收费标志4
   CR_COLC_FLG4                   string,
   -- 收费标志5
   CR_COLC_FLG5                   string,
   -- 收费标志6
   CR_COLC_FLG6                   string,
   -- 收费标志7;临时额度标志
   CR_COLC_FLG7                   string,
   -- 收费标志8;银联标志
   CR_COLC_FLG8                   string,
   -- 信用等级
   CR_CRDG                        string,
   -- 延期状态
   CR_DELAY_STS                   string,
   -- 年费收取比例
   CR_ANFE_CHG_PCT                string,
   -- 年费已扣收金额
   CR_ANFE_REV_AMT                string,
   -- 年费收取年份
   CR_ANFE_YEAR                   string,
   -- 年费未扣收月数
   ANFE_UNPAY_MONTHS              string,
   -- CVV2
   CR_CVV2                        string,
   -- 备注
   CR_FILLER_CRD                  string,
   -- 营业单位代码
   CR_OPUN_COD                    string,
   -- 有效期限
   CR_EXPD_DT                     string,
   -- 制卡状态
   CR_CRDMD_STS                   string,
   -- 主附卡标志
   CR_MNSUB_DRP                   string,
   -- 主卡卡号
   CR_PCRD_NO                     string,
   -- 注销日期
   CR_CNCLC_DT                    string,
   -- 注销状态
   CR_CNCL_STS                    string,
   -- 专用代码
   CR_SPUS_COD                    string,
   -- 版本号
   CR_VRSN_NO                     string,
   -- 卡片工本费收取比例
   R_CRD_COST_REV_RTO             string,
   -- 代发工资标志
   CR_AGENT_PAY_FLG               string,
   -- ATM上次交易日期
   CR_ATM_LTM_TX_DT               string,
   -- 客户申请编号
   CR_CUST_APLY_NO                string,
   -- 更改日期
   CR_CHG_GRNTR_DT                string,
   -- 开卡日期
   CR_OPCR_DATE                   string,
   -- 当日ATM转帐次数
   CRNT_DT_ATM_TRN_TM             string,
   -- 当日ATM转帐金额
   RNT_DT_ATM_TRN_AMT             string,
   -- 当日他行转帐次数
   CRNT_DT_TB_TRN_TM              string,
   -- 当日他行转帐金额
   CRNT_DT_TB_TRN_AMT             string,
   -- 止付日期
   CR_STPMT_DATE                  string,
   -- 发卡机构号
   CR_APP_NO                      string,
   -- 当日外币ATM取款次数
   CRNT_FX_ATM_DRW_TM             string,
   -- 当日外币ATM取款金额
   RNT_FX_AMT_DRW_AMT             string,
   -- 密码
   CR_PSWD                        string,
   -- 密码次数
   CR_PSWD_CNT                    string,
   -- 二磁道
   CR_SEC_MT_CON                  string,
   -- 二磁道校验次数
   CR_SEC_MT_CON_CNT              string,
   -- POS密码检查标志
   CR_POS_CHK_FLG                 string,
   -- IC卡主帐户
   CR_IC_PCRD_NO                  string,
   -- 换卡日期
   CR_CRD_CHG_DT                  string,
   -- IC卡数量
   CR_IC_CNT                      string,
   -- 换卡机构号
   CR_CHG_OPUN_COD                string,
   -- 失效日期出错次数
   HK_INVALI_DT_TIMES             string,
   -- #FILLER
   FILLER                         string,
   -- P9开始日期
   P9_START_DATE                  string,
   -- P9结束日期
   P9_END_DATE                    string
)
PARTITIONED BY (LOAD_DATE string)
STORED AS ORC;


-- 拉链表中间数据
DROP TABLE IF EXISTS CT_TODDC_CRCRDCRD_H_MID;

CREATE TABLE IF NOT EXISTS CT_TODDC_CRCRDCRD_H_MID (
   -- 卡号
   CR_CRD_NO                      string,
   -- 挂失日期
   CR_DL_DT                       string,
   -- 挂失状态
   CR_DL_STS                      string,
   -- 借贷别
   CR_DR_CR_COD                   string,
   -- 卡种代码
   CR_CRD_TYP_COD                 string,
   -- 卡状态
   CR_CRD_STS                     string,
   -- 客户编号
   CR_CUST_NO                     string,
   -- 营业单位代码
   CR_OPUN_COD                    string,
   -- 主附卡标志
   CR_MNSUB_DRP                   string,
   -- 主卡卡号
   CR_PCRD_NO                     string,
   -- 注销日期
   CR_CNCLC_DT                    string,
   -- 注销状态
   CR_CNCL_STS                    string,
   -- 更改日期
   CR_CHG_GRNTR_DT                string,
   -- 开卡日期
   CR_OPCR_DATE                   string,
   -- 发卡机构号
   CR_APP_NO                      string,
   -- 换卡日期
   CR_CRD_CHG_DT                  string,
   -- 换卡机构号
   CR_CHG_OPUN_COD                string,
   -- P9开始日期
   P9_START_DATE                  string,
   -- P9结束日期
   P9_END_DATE                    string
)
PARTITIONED BY (DATA_TYPE string)
STORED AS ORC;

-- 最终拉链表
DROP TABLE IF EXISTS CT_TODDC_CRCRDCRD_H;

CREATE TABLE IF NOT EXISTS CT_TODDC_CRCRDCRD_H (
   -- 卡号
   CR_CRD_NO                      string,
   -- 挂失日期
   CR_DL_DT                       string,
   -- 挂失状态
   CR_DL_STS                      string,
   -- 借贷别
   CR_DR_CR_COD                   string,
   -- 卡种代码
   CR_CRD_TYP_COD                 string,
   -- 卡状态
   CR_CRD_STS                     string,
   -- 客户编号
   CR_CUST_NO                     string,
   -- 营业单位代码
   CR_OPUN_COD                    string,
   -- 主附卡标志
   CR_MNSUB_DRP                   string,
   -- 主卡卡号
   CR_PCRD_NO                     string,
   -- 注销日期
   CR_CNCLC_DT                    string,
   -- 注销状态
   CR_CNCL_STS                    string,
   -- 更改日期
   CR_CHG_GRNTR_DT                string,
   -- 开卡日期
   CR_OPCR_DATE                   string,
   -- 发卡机构号
   CR_APP_NO                      string,
   -- 换卡日期
   CR_CRD_CHG_DT                  string,
   -- 换卡机构号
   CR_CHG_OPUN_COD                string,
   -- P9开始日期
   P9_START_DATE                  string
)
PARTITIONED BY (P9_END_DATE string)
STORED AS ORC;
