use sor;

-- Hive建表脚本
-- 个人活期存款主档: TODDC_SAACNACN_H

-- 外部表
DROP TABLE IF EXISTS EXT_TODDC_SAACNACN_H;

CREATE EXTERNAL TABLE IF NOT EXISTS EXT_TODDC_SAACNACN_H(
   -- SAACN_LL
   SAACN_LL                       string,
   -- 帐号
   SA_ACCT_NO                     string,
   -- SAACN_DB_TIMESTAMP
   SAACN_DB_TIMESTAMP             string,
   -- 活存册号
   SA_PSBK_NO                     string,
   -- 存折挂失日期
   SA_PSBK_DL_DT                  string,
   -- 当日累计取现金额（人民币）
   SA_TODAY_CSH_RMB               string,
   -- 风险等级
   SA_RISK_LEVEL                  string,
   -- 存折状态
   SA_PSBK_STS                    string,
   -- 寄对帐单标志
   SA_MBSTMT_FLG                  string,
   -- 经营管理机构
   SA_OPAC_INSTN_NO               string,
   -- 开户金额
   SA_OPAC_AMT                    string,
   -- 开户日期
   SA_OPAC_DT                     string,
   -- 记账机构
   SA_RCRD_INSTN_NO               string,
   -- 原账户控制状态
   SA_ACCT_ORG_CTL_STS            string,
   -- 医保卡标志
   SA_YBK_FLG                     string,
   -- 个人外币账户性质
   SA_ACCT_CHAR_FX                string,
   -- 客户编号
   SA_CUST_NO                     string,
   -- 客户名称
   SA_CUST_NAME                   string,
   -- 联系人编号
   SA_CONNTR_NO                   string,
   -- 密码
   SA_CRPT_PIN                    string,
   -- 密码挂失日期
   SA_PSWD_DL_DT                  string,
   -- 密码状态
   SA_PSWD_STS                    string,
   -- 明细笔数
   SA_DET_ITEM_N                  string,
   -- 销户机构号
   SA_CACCT_INSTN_NO              string,
   -- 销户日期
   SA_CACCT_DT                    string,
   -- 页行数
   SA_PGLN_TOTL                   string,
   -- 已登折明细数
   SA_AENTR_DET_TOTL              string,
   -- 已对帐明细数
   SA_ACKAC_DET_TOTL              string,
   -- 印鉴卡编号
   SA_SLCRD_NO                    string,
   -- 约定机构存取标志
   SA_PRDS_INSTN_DPDW_FLG         string,
   -- 帐别
   SA_ACCT_TYP                    string,
   -- 帐户性质
   SA_ACCT_CHAR                   string,
   -- 支取方式
   SA_DRW_TYP                     string,
   -- 对帐单地址代码
   SA_ASTMT_ADDR_COD              string,
   -- 印鉴状态
   SA_SEAL_STS                    string,
   -- 帐簿当前页
   SA_ACC_PAGE_NO                 string,
   -- 已打印最大序号
   SA_PRINTED_MAX_NO              string,
   -- 未打印帐簿笔数
   SA_ACC_UNPRINT_NO              string,
   -- 开户柜员号
   SA_OPAC_TL_NO                  string,
   -- 销户柜员号
   SA_CACCT_TL_NO                 string,
   -- 计息标志
   SA_INTC_FLG                    string,
   -- 印鉴挂失日期
   SA_SEAL_DL_DT                  string,
   -- 结算手续费收取方式
   SA_STLM_SVC_STY                string,
   -- 贷款种类
   SA_DEP_TYP                     string,
   -- 页数
   SA_PAGESUM_N                   string,
   -- 钞汇属性
   SA_CURR_CHAR                   string,
   -- 起用日期
   SA_AVAL_DT                     string,
   -- 外汇买卖质押炒汇签约标志
   SA_XT_SIGN_FLG                 string,
   -- 理财卡一户通备付金签约标志
   SA_YHT_SIGN_FLG                string,
   -- 校园卡标志
   SA_XYK_FLG                     string,
   -- 支付限额控制标志
   SA_LMT_CTL_FLG                 string,
   -- 集团客户虚账户标志
   SA_VIR_ACCT_FLG                string,
   -- 集团现金池签约标志
   SA_GRP_SIGN_FLG                string,
   -- 外汇保证金帐户标志
   SA_XT_ACCT_FLG                 string,
   -- 密码出错次数
   SA_PSWD_ERR_TIMES              string,
   -- 当日累计取现金额（美金）
   SA_TODAY_CSH_USD               string,
   -- 卡号
   SA_CARD_NO                     string,
   -- 利息税计税标志
   SA_INT_TAX_FLG                 string,
   -- 帐户控制状态
   SA_ACCT_CTL_STS                string,
   -- 综合理财标志
   SA_FS_STS                      string,
   -- 承上页标志
   SA_NEXT_PAGE_FLG_N             string,
   -- 签约标志
   SA_SIGN_FLG                    string,
   -- 是否贷记卡指定还款帐号
   SA_CCR_FLG                     string,
   -- 上次明细日
   SA_LAST_TXN_DT                 string,
   -- 通兑范围
   SA_DPDW_RANG                   string,
   -- 关注种类个数
   SA_RECOG_TYP_NUM_N             string,
   -- 原存款种类
   SA_ORG_DEP_TYPE                string,
   -- 最后取现日期
   SA_LAST_CSH_DT                 string,
   -- 共管帐户标志
   SA_GG_ACCT_FLG                 string,
   -- 非冻结委托次数
   SA_NON_FRZ_CONSIGN_TIME        string,
   -- 行政区域代码
   SA_DIST_COD                    string,
   -- 存折印刷号1
   SA_PSBK_PRT_NO1                string,
   -- 按机构拆分字段
   P9_SPLIT_BRANCH_CD             string,
   -- P9开始日期
   P9_START_DATE                  string,
   -- P9开始批次号
   P9_START_BATCH                 string,
   -- P9结束日期
   P9_END_DATE                    string,
   -- P9结束批次号
   P9_END_BATCH                   string,
   -- P9删除标志
   P9_DEL_FLAG                    string,
   -- P9作业名
   P9_JOB_NAME                    string,
   -- 假名账户标志
   SA_TSF_FLG                     string,
   -- 家庭现金管理标志
   SA_FAMILY_FLG                  string
)
PARTITIONED BY (LOAD_DATE string)
STORED AS TEXTFILE;

-- ORC内部表，节约存储空间
DROP TABLE IF EXISTS INN_TODDC_SAACNACN_H;

CREATE TABLE IF NOT EXISTS INN_TODDC_SAACNACN_H(
   -- SAACN_LL
   SAACN_LL                       string,
   -- 帐号
   SA_ACCT_NO                     string,
   -- SAACN_DB_TIMESTAMP
   SAACN_DB_TIMESTAMP             string,
   -- 活存册号
   SA_PSBK_NO                     string,
   -- 存折挂失日期
   SA_PSBK_DL_DT                  string,
   -- 当日累计取现金额（人民币）
   SA_TODAY_CSH_RMB               string,
   -- 风险等级
   SA_RISK_LEVEL                  string,
   -- 存折状态
   SA_PSBK_STS                    string,
   -- 寄对帐单标志
   SA_MBSTMT_FLG                  string,
   -- 经营管理机构
   SA_OPAC_INSTN_NO               string,
   -- 开户金额
   SA_OPAC_AMT                    string,
   -- 开户日期
   SA_OPAC_DT                     string,
   -- 记账机构
   SA_RCRD_INSTN_NO               string,
   -- 原账户控制状态
   SA_ACCT_ORG_CTL_STS            string,
   -- 医保卡标志
   SA_YBK_FLG                     string,
   -- 个人外币账户性质
   SA_ACCT_CHAR_FX                string,
   -- 客户编号
   SA_CUST_NO                     string,
   -- 客户名称
   SA_CUST_NAME                   string,
   -- 联系人编号
   SA_CONNTR_NO                   string,
   -- 密码
   SA_CRPT_PIN                    string,
   -- 密码挂失日期
   SA_PSWD_DL_DT                  string,
   -- 密码状态
   SA_PSWD_STS                    string,
   -- 明细笔数
   SA_DET_ITEM_N                  string,
   -- 销户机构号
   SA_CACCT_INSTN_NO              string,
   -- 销户日期
   SA_CACCT_DT                    string,
   -- 页行数
   SA_PGLN_TOTL                   string,
   -- 已登折明细数
   SA_AENTR_DET_TOTL              string,
   -- 已对帐明细数
   SA_ACKAC_DET_TOTL              string,
   -- 印鉴卡编号
   SA_SLCRD_NO                    string,
   -- 约定机构存取标志
   SA_PRDS_INSTN_DPDW_FLG         string,
   -- 帐别
   SA_ACCT_TYP                    string,
   -- 帐户性质
   SA_ACCT_CHAR                   string,
   -- 支取方式
   SA_DRW_TYP                     string,
   -- 对帐单地址代码
   SA_ASTMT_ADDR_COD              string,
   -- 印鉴状态
   SA_SEAL_STS                    string,
   -- 帐簿当前页
   SA_ACC_PAGE_NO                 string,
   -- 已打印最大序号
   SA_PRINTED_MAX_NO              string,
   -- 未打印帐簿笔数
   SA_ACC_UNPRINT_NO              string,
   -- 开户柜员号
   SA_OPAC_TL_NO                  string,
   -- 销户柜员号
   SA_CACCT_TL_NO                 string,
   -- 计息标志
   SA_INTC_FLG                    string,
   -- 印鉴挂失日期
   SA_SEAL_DL_DT                  string,
   -- 结算手续费收取方式
   SA_STLM_SVC_STY                string,
   -- 贷款种类
   SA_DEP_TYP                     string,
   -- 页数
   SA_PAGESUM_N                   string,
   -- 钞汇属性
   SA_CURR_CHAR                   string,
   -- 起用日期
   SA_AVAL_DT                     string,
   -- 外汇买卖质押炒汇签约标志
   SA_XT_SIGN_FLG                 string,
   -- 理财卡一户通备付金签约标志
   SA_YHT_SIGN_FLG                string,
   -- 校园卡标志
   SA_XYK_FLG                     string,
   -- 支付限额控制标志
   SA_LMT_CTL_FLG                 string,
   -- 集团客户虚账户标志
   SA_VIR_ACCT_FLG                string,
   -- 集团现金池签约标志
   SA_GRP_SIGN_FLG                string,
   -- 外汇保证金帐户标志
   SA_XT_ACCT_FLG                 string,
   -- 密码出错次数
   SA_PSWD_ERR_TIMES              string,
   -- 当日累计取现金额（美金）
   SA_TODAY_CSH_USD               string,
   -- 卡号
   SA_CARD_NO                     string,
   -- 利息税计税标志
   SA_INT_TAX_FLG                 string,
   -- 帐户控制状态
   SA_ACCT_CTL_STS                string,
   -- 综合理财标志
   SA_FS_STS                      string,
   -- 承上页标志
   SA_NEXT_PAGE_FLG_N             string,
   -- 签约标志
   SA_SIGN_FLG                    string,
   -- 是否贷记卡指定还款帐号
   SA_CCR_FLG                     string,
   -- 上次明细日
   SA_LAST_TXN_DT                 string,
   -- 通兑范围
   SA_DPDW_RANG                   string,
   -- 关注种类个数
   SA_RECOG_TYP_NUM_N             string,
   -- 原存款种类
   SA_ORG_DEP_TYPE                string,
   -- 最后取现日期
   SA_LAST_CSH_DT                 string,
   -- 共管帐户标志
   SA_GG_ACCT_FLG                 string,
   -- 非冻结委托次数
   SA_NON_FRZ_CONSIGN_TIME        string,
   -- 行政区域代码
   SA_DIST_COD                    string,
   -- 存折印刷号1
   SA_PSBK_PRT_NO1                string,
   -- P9开始日期
   P9_START_DATE                  string,
   -- P9结束日期
   P9_END_DATE                    string,
   -- 假名账户标志
   SA_TSF_FLG                     string,
   -- 家庭现金管理标志
   SA_FAMILY_FLG                  string
)
PARTITIONED BY (LOAD_DATE string)
STORED AS ORC;


-- 拉链表中间数据
DROP TABLE IF EXISTS CT_TODDC_SAACNACN_H_MID;

CREATE TABLE IF NOT EXISTS CT_TODDC_SAACNACN_H_MID (
   -- 帐号
   SA_ACCT_NO                     string,
   -- 开户金额
   SA_OPAC_AMT                    string,
   -- 开户日期
   SA_OPAC_DT                     string,
   -- 记账机构
   SA_RCRD_INSTN_NO               string,
   -- 客户编号
   SA_CUST_NO                     string,
   -- 客户名称
   SA_CUST_NAME                   string,
   -- 联系人编号
   SA_CONNTR_NO                   string,
   -- 销户机构号
   SA_CACCT_INSTN_NO              string,
   -- 销户日期
   SA_CACCT_DT                    string,
   -- 开户柜员号
   SA_OPAC_TL_NO                  string,
   -- 销户柜员号
   SA_CACCT_TL_NO                 string,
   -- 理财卡一户通备付金签约标志
   SA_YHT_SIGN_FLG                string,
   -- 校园卡标志
   SA_XYK_FLG                     string,
   -- 支付限额控制标志
   SA_LMT_CTL_FLG                 string,
   -- 卡号
   SA_CARD_NO                     string,
   -- 综合理财标志
   SA_FS_STS                      string,
   -- 是否贷记卡指定还款帐号
   SA_CCR_FLG                     string,
   -- P9开始日期
   P9_START_DATE                  string,
   -- P9结束日期
   P9_END_DATE                    string
)
PARTITIONED BY (DATA_TYPE string)
STORED AS ORC;

-- 最终拉链表
DROP TABLE IF EXISTS CT_TODDC_SAACNACN_H;

CREATE TABLE IF NOT EXISTS CT_TODDC_SAACNACN_H (
   -- 帐号
   SA_ACCT_NO                     string,
   -- 开户金额
   SA_OPAC_AMT                    string,
   -- 开户日期
   SA_OPAC_DT                     string,
   -- 记账机构
   SA_RCRD_INSTN_NO               string,
   -- 客户编号
   SA_CUST_NO                     string,
   -- 客户名称
   SA_CUST_NAME                   string,
   -- 联系人编号
   SA_CONNTR_NO                   string,
   -- 销户机构号
   SA_CACCT_INSTN_NO              string,
   -- 销户日期
   SA_CACCT_DT                    string,
   -- 开户柜员号
   SA_OPAC_TL_NO                  string,
   -- 销户柜员号
   SA_CACCT_TL_NO                 string,
   -- 理财卡一户通备付金签约标志
   SA_YHT_SIGN_FLG                string,
   -- 校园卡标志
   SA_XYK_FLG                     string,
   -- 支付限额控制标志
   SA_LMT_CTL_FLG                 string,
   -- 卡号
   SA_CARD_NO                     string,
   -- 综合理财标志
   SA_FS_STS                      string,
   -- 是否贷记卡指定还款帐号
   SA_CCR_FLG                     string,
   -- P9开始日期
   P9_START_DATE                  string
)
PARTITIONED BY (P9_END_DATE string)
STORED AS ORC;
