#!/bin/sh

#引用基础Shell函数库
source /home/ap/dip_ts150/ts150_script/ccb_risk_scoring/base.sh

#解释命令行参数
logdate_arg $*

#新集群登陆
hadoop_login

db=train

IN_CUR_HIVE="train_feature_trad_flow_first_a train_feature_card_90_day train_feature_crdt_90_day"
OUT_CUR_HIVE="train_feature_trad_flow_a"

p9_data_date=$log_date

feature()
{
beeline <<!
use $db;

insert overwrite table train_feature_trad_flow_a partition (p9_data_date='$p9_data_date')

select 
    a.SA_ACCT_NO,
    a.SA_DDP_ACCT_NO_DET_N,
    a.CHANL_TYPE,
    a.SA_APP_TX_CODE,
    a.SA_TX_AMT,
    a.SA_DDP_ACCT_BAL,
    a.SA_DSCRP_COD,
    a.SA_SVC,
    a.SA_EC_FLG,
    a.tx_last_time,
    a.JD_FLAG,
    a.IS_ZZ,
    a.IS_CARD_JYLX_FIRST,
    a.IS_CARD_SB_FIRST,
    a.IS_CARD_ZZ_FIRST,
    a.IS_CARD_JG_FIRST,
    a.IS_CARD_IP_FIRST,
    a.IS_CARD_AREA_FIRST,
    a.IS_KH,
    a.IS_BR,
    a.IS_PASS_JYLX_FIRST,
    a.IS_PASS_SB_FIRST,
    a.IS_PASS_ZZ_FIRST,
    a.IS_PASS_JG_FIRST,
    a.IS_PASS_IP_FIRST,
    a.IS_PASS_AREA_FIRST,
    a.ASS_ACCT_DR_TIME,

    b.all_cur_day_trade_num,
    b.all_cur_day_trade_amt,
    b.all_cur_day_in_num,
    b.all_cur_day_in_amt,
    b.all_cur_day_out_num,
    b.all_cur_day_out_amt,
    b.all_cur_day_trn_out_num,
    b.all_cur_day_trn_out_amt,
    b.all_cur_day_500_out_num,
    b.all_cur_day_500_out_amt,
    b.all_cur_day_10000_out_num,
    b.all_cur_day_10000_out_amt,
    b.all_cur_day_20000_out_num,
    b.all_cur_day_20000_out_amt,
    b.all_cur_day_more_out_num,
    b.all_cur_day_more_out_amt,
    b.atm_cur_day_dep_num,
    b.atm_cur_day_dep_amt,
    b.atm_cur_day_wd_num,
    b.atm_cur_day_wd_amt,
    b.atm_cur_day_trn_num,
    b.atm_cur_day_trn_amt,
    b.pos_cur_day_cnsmp_num,
    b.pos_cur_day_cnsmp_amt,
    b.nb_cur_day_out_num,
    b.nb_cur_day_out_amt,
    b.mb_cur_day_out_num,
    b.mb_cur_day_out_amt,
    b.all_7_day_trade_num,
    b.all_7_day_trade_amt,
    b.all_7_day_in_num,
    b.all_7_day_in_amt,
    b.all_7_day_out_num,
    b.all_7_day_out_amt,
    b.all_7_day_trn_out_num,
    b.all_7_day_trn_out_amt,
    b.all_7_day_500_out_num,
    b.all_7_day_500_out_amt,
    b.all_7_day_10000_out_num,
    b.all_7_day_10000_out_amt,
    b.all_7_day_20000_out_num,
    b.all_7_day_20000_out_amt,
    b.all_7_day_more_out_num,
    b.all_7_day_more_out_amt,
    b.atm_7_day_dep_num,
    b.atm_7_day_dep_amt,
    b.atm_7_day_wd_num,
    b.atm_7_day_wd_amt,
    b.atm_7_day_trn_num,
    b.atm_7_day_trn_amt,
    b.pos_7_day_cnsmp_num,
    b.pos_7_day_cnsmp_amt,
    b.nb_7_day_out_num,
    b.nb_7_day_out_amt,
    b.mb_7_day_out_num,
    b.mb_7_day_out_amt,
    b.all_30_day_trade_num,
    b.all_30_day_trade_amt,
    b.all_30_day_in_num,
    b.all_30_day_in_amt,
    b.all_30_day_out_num,
    b.all_30_day_out_amt,
    b.all_30_day_trn_out_num,
    b.all_30_day_trn_out_amt,
    b.all_30_day_500_out_num,
    b.all_30_day_500_out_amt,
    b.all_30_day_10000_out_num,
    b.all_30_day_10000_out_amt,
    b.all_30_day_20000_out_num,
    b.all_30_day_20000_out_amt,
    b.all_30_day_more_out_num,
    b.all_30_day_more_out_amt,
    b.atm_30_day_dep_num,
    b.atm_30_day_dep_amt,
    b.atm_30_day_wd_num,
    b.atm_30_day_wd_amt,
    b.atm_30_day_trn_num,
    b.atm_30_day_trn_amt,
    b.pos_30_day_cnsmp_num,
    b.pos_30_day_cnsmp_amt,
    b.nb_30_day_out_num,
    b.nb_30_day_out_amt,
    b.mb_30_day_out_num,
    b.mb_30_day_out_amt,
    b.all_90_day_trade_num,
    b.all_90_day_trade_amt,
    b.all_90_day_in_num,
    b.all_90_day_in_amt,
    b.all_90_day_out_num,
    b.all_90_day_out_amt,
    b.all_90_day_trn_out_num,
    b.all_90_day_trn_out_amt,
    b.all_90_day_500_out_num,
    b.all_90_day_500_out_amt,
    b.all_90_day_10000_out_num,
    b.all_90_day_10000_out_amt,
    b.all_90_day_20000_out_num,
    b.all_90_day_20000_out_amt,
    b.all_90_day_more_out_num,
    b.all_90_day_more_out_amt,
    b.atm_90_day_dep_num,
    b.atm_90_day_dep_amt,
    b.atm_90_day_wd_num,
    b.atm_90_day_wd_amt,
    b.atm_90_day_trn_num,
    b.atm_90_day_trn_amt,
    b.pos_90_day_cnsmp_num,
    b.pos_90_day_cnsmp_amt,
    b.nb_90_day_out_num,
    b.nb_90_day_out_amt,
    b.mb_90_day_out_num,
    b.mb_90_day_out_amt,

    c.all_cur_day_trade_num,
    c.all_cur_day_trade_amt,
    c.all_cur_day_in_num,
    c.all_cur_day_in_amt,
    c.all_cur_day_out_num,
    c.all_cur_day_out_amt,
    c.all_cur_day_trn_out_num,
    c.all_cur_day_trn_out_amt,
    c.all_cur_day_500_out_num,
    c.all_cur_day_500_out_amt,
    c.all_cur_day_10000_out_num,
    c.all_cur_day_10000_out_amt,
    c.all_cur_day_20000_out_num,
    c.all_cur_day_20000_out_amt,
    c.all_cur_day_more_out_num,
    c.all_cur_day_more_out_amt,
    c.atm_cur_day_dep_num,
    c.atm_cur_day_dep_amt,
    c.atm_cur_day_wd_num,
    c.atm_cur_day_wd_amt,
    c.atm_cur_day_trn_num,
    c.atm_cur_day_trn_amt,
    c.pos_cur_day_cnsmp_num,
    c.pos_cur_day_cnsmp_amt,
    c.nb_cur_day_out_num,
    c.nb_cur_day_out_amt,
    c.mb_cur_day_out_num,
    c.mb_cur_day_out_amt,
    c.all_7_day_trade_num,
    c.all_7_day_trade_amt,
    c.all_7_day_in_num,
    c.all_7_day_in_amt,
    c.all_7_day_out_num,
    c.all_7_day_out_amt,
    c.all_7_day_trn_out_num,
    c.all_7_day_trn_out_amt,
    c.all_7_day_500_out_num,
    c.all_7_day_500_out_amt,
    c.all_7_day_10000_out_num,
    c.all_7_day_10000_out_amt,
    c.all_7_day_20000_out_num,
    c.all_7_day_20000_out_amt,
    c.all_7_day_more_out_num,
    c.all_7_day_more_out_amt,
    c.atm_7_day_dep_num,
    c.atm_7_day_dep_amt,
    c.atm_7_day_wd_num,
    c.atm_7_day_wd_amt,
    c.atm_7_day_trn_num,
    c.atm_7_day_trn_amt,
    c.pos_7_day_cnsmp_num,
    c.pos_7_day_cnsmp_amt,
    c.nb_7_day_out_num,
    c.nb_7_day_out_amt,
    c.mb_7_day_out_num,
    c.mb_7_day_out_amt,
    c.all_30_day_trade_num,
    c.all_30_day_trade_amt,
    c.all_30_day_in_num,
    c.all_30_day_in_amt,
    c.all_30_day_out_num,
    c.all_30_day_out_amt,
    c.all_30_day_trn_out_num,
    c.all_30_day_trn_out_amt,
    c.all_30_day_500_out_num,
    c.all_30_day_500_out_amt,
    c.all_30_day_10000_out_num,
    c.all_30_day_10000_out_amt,
    c.all_30_day_20000_out_num,
    c.all_30_day_20000_out_amt,
    c.all_30_day_more_out_num,
    c.all_30_day_more_out_amt,
    c.atm_30_day_dep_num,
    c.atm_30_day_dep_amt,
    c.atm_30_day_wd_num,
    c.atm_30_day_wd_amt,
    c.atm_30_day_trn_num,
    c.atm_30_day_trn_amt,
    c.pos_30_day_cnsmp_num,
    c.pos_30_day_cnsmp_amt,
    c.nb_30_day_out_num,
    c.nb_30_day_out_amt,
    c.mb_30_day_out_num,
    c.mb_30_day_out_amt,
    c.all_90_day_trade_num,
    c.all_90_day_trade_amt,
    c.all_90_day_in_num,
    c.all_90_day_in_amt,
    c.all_90_day_out_num,
    c.all_90_day_out_amt,
    c.all_90_day_trn_out_num,
    c.all_90_day_trn_out_amt,
    c.all_90_day_500_out_num,
    c.all_90_day_500_out_amt,
    c.all_90_day_10000_out_num,
    c.all_90_day_10000_out_amt,
    c.all_90_day_20000_out_num,
    c.all_90_day_20000_out_amt,
    c.all_90_day_more_out_num,
    c.all_90_day_more_out_amt,
    c.atm_90_day_dep_num,
    c.atm_90_day_dep_amt,
    c.atm_90_day_wd_num,
    c.atm_90_day_wd_amt,
    c.atm_90_day_trn_num,
    c.atm_90_day_trn_amt,
    c.pos_90_day_cnsmp_num,
    c.pos_90_day_cnsmp_amt,
    c.nb_90_day_out_num,
    c.nb_90_day_out_amt,
    c.mb_90_day_out_num,
    c.mb_90_day_out_amt    

from 
(select * from train_feature_trad_flow_first_a where p9_data_date='${p9_data_date}') a

inner join(
 select * from train_feature_card_90_day where p9_data_date='${p9_data_date}'
) b 
 on a.card_no=b.card_no

inner join(
 select * from train_feature_crdt_90_day where p9_data_date='${p9_data_date}'
) c 
 on a.crdt_no=c.crdt_no;

!
}

run()
{
  feature
}

