batch=0327
db=verify_2

#创建卡特征表

create_table(){

data_date=$1

table_name=train_feature_trad_flow_a_${batch}_${data_date}

beeline <<!
use ${db};

drop table $table_name;

create table if not exists $table_name(
    mark_flag string,
    flow_no string,
    CHANL_TYPE string,

    SA_APP_TX_CODE string,
    SA_TX_AMT string,
    SA_DDP_ACCT_BAL string,
    SA_DSCRP_COD string,
    SA_SVC string,
    SA_EC_FLG string,

    tx_last_time string,
    JD_FLAG string,
    IS_ZZ string,
    IS_CARD_JYLX_FIRST string,
    IS_CARD_SB_FIRST string,
    IS_CARD_ZZ_FIRST string,
    IS_CARD_JG_FIRST string,
    IS_CARD_IP_FIRST string,
    IS_KH string,
    IS_BR string,
    IS_PASS_JYLX_FIRST string,
    IS_PASS_SB_FIRST string,
    IS_PASS_ZZ_FIRST string,
    IS_PASS_JG_FIRST string,
    IS_PASS_IP_FIRST string,

    ASS_ACCT_DR_TIME string,

    card_all_cur_day_trade_num string,
    card_all_cur_day_trade_amt string,
    card_all_cur_day_in_num string,
    card_all_cur_day_in_amt string,
    card_all_cur_day_out_num string,
    card_all_cur_day_out_amt string,
    card_all_cur_day_trn_out_num string,
    card_all_cur_day_trn_out_amt string,
    card_all_cur_day_500_out_num string,
    card_all_cur_day_500_out_amt string,
    card_all_cur_day_10000_out_num string,
    card_all_cur_day_10000_out_amt string,
    card_all_cur_day_20000_out_num string,
    card_all_cur_day_20000_out_amt string,
    card_all_cur_day_more_out_num string,
    card_all_cur_day_more_out_amt string,
    card_atm_cur_day_dep_num string,
    card_atm_cur_day_dep_amt string,
    card_atm_cur_day_wd_num string,
    card_atm_cur_day_wd_amt string,
    card_atm_cur_day_trn_num string,
    card_atm_cur_day_trn_amt string,
    card_pos_cur_day_cnsmp_num string,
    card_pos_cur_day_cnsmp_amt string,
    card_nb_cur_day_out_num string,
    card_nb_cur_day_out_amt string,
    card_mb_cur_day_out_num string,
    card_mb_cur_day_out_amt string,
    card_all_7_day_trade_num string,
    card_all_7_day_trade_amt string,
    card_all_7_day_in_num string,
    card_all_7_day_in_amt string,
    card_all_7_day_out_num string,
    card_all_7_day_out_amt string,
    card_all_7_day_trn_out_num string,
    card_all_7_day_trn_out_amt string,
    card_all_7_day_500_out_num string,
    card_all_7_day_500_out_amt string,
    card_all_7_day_10000_out_num string,
    card_all_7_day_10000_out_amt string,
    card_all_7_day_20000_out_num string,
    card_all_7_day_20000_out_amt string,
    card_all_7_day_more_out_num string,
    card_all_7_day_more_out_amt string,
    card_atm_7_day_dep_num string,
    card_atm_7_day_dep_amt string,
    card_atm_7_day_wd_num string,
    card_atm_7_day_wd_amt string,
    card_atm_7_day_trn_num string,
    card_atm_7_day_trn_amt string,
    card_pos_7_day_cnsmp_num string,
    card_pos_7_day_cnsmp_amt string,
    card_nb_7_day_out_num string,
    card_nb_7_day_out_amt string,
    card_mb_7_day_out_num string,
    card_mb_7_day_out_amt string,
    card_all_30_day_trade_num string,
    card_all_30_day_trade_amt string,
    card_all_30_day_in_num string,
    card_all_30_day_in_amt string,
    card_all_30_day_out_num string,
    card_all_30_day_out_amt string,
    card_all_30_day_trn_out_num string,
    card_all_30_day_trn_out_amt string,
    card_all_30_day_500_out_num string,
    card_all_30_day_500_out_amt string,
    card_all_30_day_10000_out_num string,
    card_all_30_day_10000_out_amt string,
    card_all_30_day_20000_out_num string,
    card_all_30_day_20000_out_amt string,
    card_all_30_day_more_out_num string,
    card_all_30_day_more_out_amt string,
    card_atm_30_day_dep_num string,
    card_atm_30_day_dep_amt string,
    card_atm_30_day_wd_num string,
    card_atm_30_day_wd_amt string,
    card_atm_30_day_trn_num string,
    card_atm_30_day_trn_amt string,
    card_pos_30_day_cnsmp_num string,
    card_pos_30_day_cnsmp_amt string,
    card_nb_30_day_out_num string,
    card_nb_30_day_out_amt string,
    card_mb_30_day_out_num string,
    card_mb_30_day_out_amt string,
    card_all_90_day_trade_num string,
    card_all_90_day_trade_amt string,
    card_all_90_day_in_num string,
    card_all_90_day_in_amt string,
    card_all_90_day_out_num string,
    card_all_90_day_out_amt string,
    card_all_90_day_trn_out_num string,
    card_all_90_day_trn_out_amt string,
    card_all_90_day_500_out_num string,
    card_all_90_day_500_out_amt string,
    card_all_90_day_10000_out_num string,
    card_all_90_day_10000_out_amt string,
    card_all_90_day_20000_out_num string,
    card_all_90_day_20000_out_amt string,
    card_all_90_day_more_out_num string,
    card_all_90_day_more_out_amt string,
    card_atm_90_day_dep_num string,
    card_atm_90_day_dep_amt string,
    card_atm_90_day_wd_num string,
    card_atm_90_day_wd_amt string,
    card_atm_90_day_trn_num string,
    card_atm_90_day_trn_amt string,
    card_pos_90_day_cnsmp_num string,
    card_pos_90_day_cnsmp_amt string,
    card_nb_90_day_out_num string,
    card_nb_90_day_out_amt string,
    card_mb_90_day_out_num string,
    card_mb_90_day_out_amt string,

    pass_all_cur_day_trade_num string,
    pass_all_cur_day_trade_amt string,
    pass_all_cur_day_in_num string,
    pass_all_cur_day_in_amt string,
    pass_all_cur_day_out_num string,
    pass_all_cur_day_out_amt string,
    pass_all_cur_day_trn_out_num string,
    pass_all_cur_day_trn_out_amt string,
    pass_all_cur_day_500_out_num string,
    pass_all_cur_day_500_out_amt string,
    pass_all_cur_day_10000_out_num string,
    pass_all_cur_day_10000_out_amt string,
    pass_all_cur_day_20000_out_num string,
    pass_all_cur_day_20000_out_amt string,
    pass_all_cur_day_more_out_num string,
    pass_all_cur_day_more_out_amt string,
    pass_atm_cur_day_dep_num string,
    pass_atm_cur_day_dep_amt string,
    pass_atm_cur_day_wd_num string,
    pass_atm_cur_day_wd_amt string,
    pass_atm_cur_day_trn_num string,
    pass_atm_cur_day_trn_amt string,
    pass_pos_cur_day_cnsmp_num string,
    pass_pos_cur_day_cnsmp_amt string,
    pass_nb_cur_day_out_num string,
    pass_nb_cur_day_out_amt string,
    pass_mb_cur_day_out_num string,
    pass_mb_cur_day_out_amt string,
    pass_all_7_day_trade_num string,
    pass_all_7_day_trade_amt string,
    pass_all_7_day_in_num string,
    pass_all_7_day_in_amt string,
    pass_all_7_day_out_num string,
    pass_all_7_day_out_amt string,
    pass_all_7_day_trn_out_num string,
    pass_all_7_day_trn_out_amt string,
    pass_all_7_day_500_out_num string,
    pass_all_7_day_500_out_amt string,
    pass_all_7_day_10000_out_num string,
    pass_all_7_day_10000_out_amt string,
    pass_all_7_day_20000_out_num string,
    pass_all_7_day_20000_out_amt string,
    pass_all_7_day_more_out_num string,
    pass_all_7_day_more_out_amt string,
    pass_atm_7_day_dep_num string,
    pass_atm_7_day_dep_amt string,
    pass_atm_7_day_wd_num string,
    pass_atm_7_day_wd_amt string,
    pass_atm_7_day_trn_num string,
    pass_atm_7_day_trn_amt string,
    pass_pos_7_day_cnsmp_num string,
    pass_pos_7_day_cnsmp_amt string,
    pass_nb_7_day_out_num string,
    pass_nb_7_day_out_amt string,
    pass_mb_7_day_out_num string,
    pass_mb_7_day_out_amt string,
    pass_all_30_day_trade_num string,
    pass_all_30_day_trade_amt string,
    pass_all_30_day_in_num string,
    pass_all_30_day_in_amt string,
    pass_all_30_day_out_num string,
    pass_all_30_day_out_amt string,
    pass_all_30_day_trn_out_num string,
    pass_all_30_day_trn_out_amt string,
    pass_all_30_day_500_out_num string,
    pass_all_30_day_500_out_amt string,
    pass_all_30_day_10000_out_num string,
    pass_all_30_day_10000_out_amt string,
    pass_all_30_day_20000_out_num string,
    pass_all_30_day_20000_out_amt string,
    pass_all_30_day_more_out_num string,
    pass_all_30_day_more_out_amt string,
    pass_atm_30_day_dep_num string,
    pass_atm_30_day_dep_amt string,
    pass_atm_30_day_wd_num string,
    pass_atm_30_day_wd_amt string,
    pass_atm_30_day_trn_num string,
    pass_atm_30_day_trn_amt string,
    pass_pos_30_day_cnsmp_num string,
    pass_pos_30_day_cnsmp_amt string,
    pass_nb_30_day_out_num string,
    pass_nb_30_day_out_amt string,
    pass_mb_30_day_out_num string,
    pass_mb_30_day_out_amt string,
    pass_all_90_day_trade_num string,
    pass_all_90_day_trade_amt string,
    pass_all_90_day_in_num string,
    pass_all_90_day_in_amt string,
    pass_all_90_day_out_num string,
    pass_all_90_day_out_amt string,
    pass_all_90_day_trn_out_num string,
    pass_all_90_day_trn_out_amt string,
    pass_all_90_day_500_out_num string,
    pass_all_90_day_500_out_amt string,
    pass_all_90_day_10000_out_num string,
    pass_all_90_day_10000_out_amt string,
    pass_all_90_day_20000_out_num string,
    pass_all_90_day_20000_out_amt string,
    pass_all_90_day_more_out_num string,
    pass_all_90_day_more_out_amt string,
    pass_atm_90_day_dep_num string,
    pass_atm_90_day_dep_amt string,
    pass_atm_90_day_wd_num string,
    pass_atm_90_day_wd_amt string,
    pass_atm_90_day_trn_num string,
    pass_atm_90_day_trn_amt string,
    pass_pos_90_day_cnsmp_num string,
    pass_pos_90_day_cnsmp_amt string,
    pass_nb_90_day_out_num string,
    pass_nb_90_day_out_amt string,
    pass_mb_90_day_out_num string,
    pass_mb_90_day_out_amt string,
    p9_data_date string
)
stored as ORC;

!
}


insert()
{

data_date=$1

table_name=train_feature_trad_flow_a_${batch}_${data_date}

beeline <<!

use ${db};

insert overwrite table $table_name
select 
    '0' as mark_flag,
    concat(a.SA_ACCT_NO, '_', a.SA_DDP_ACCT_NO_DET_N) as flow_no,
    a.CHANL_TYPE ,
    a.SA_APP_TX_CODE ,
    a.SA_TX_AMT ,
    a.SA_DDP_ACCT_BAL ,
    a.SA_DSCRP_COD ,
    a.SA_SVC ,
    a.SA_EC_FLG ,
    a.tx_last_time ,
    a.JD_FLAG ,
    a.IS_ZZ ,
    a.IS_CARD_JYLX_FIRST ,
    a.IS_CARD_SB_FIRST ,
    a.IS_CARD_ZZ_FIRST ,
    a.IS_CARD_JG_FIRST ,
    a.IS_CARD_IP_FIRST ,
    a.IS_KH ,
    a.IS_BR ,
    a.IS_PASS_JYLX_FIRST ,
    a.IS_PASS_SB_FIRST ,
    a.IS_PASS_ZZ_FIRST ,
    a.IS_PASS_JG_FIRST ,
    a.IS_PASS_IP_FIRST ,
    a.ASS_ACCT_DR_TIME ,
    a.card_all_cur_day_trade_num ,
    a.card_all_cur_day_trade_amt ,
    a.card_all_cur_day_in_num ,
    a.card_all_cur_day_in_amt ,
    a.card_all_cur_day_out_num ,
    a.card_all_cur_day_out_amt ,
    a.card_all_cur_day_trn_out_num ,
    a.card_all_cur_day_trn_out_amt ,
    a.card_all_cur_day_500_out_num ,
    a.card_all_cur_day_500_out_amt ,
    a.card_all_cur_day_10000_out_num ,
    a.card_all_cur_day_10000_out_amt ,
    a.card_all_cur_day_20000_out_num ,
    a.card_all_cur_day_20000_out_amt ,
    a.card_all_cur_day_more_out_num ,
    a.card_all_cur_day_more_out_amt ,
    a.card_atm_cur_day_dep_num ,
    a.card_atm_cur_day_dep_amt ,
    a.card_atm_cur_day_wd_num ,
    a.card_atm_cur_day_wd_amt ,
    a.card_atm_cur_day_trn_num ,
    a.card_atm_cur_day_trn_amt ,
    a.card_pos_cur_day_cnsmp_num ,
    a.card_pos_cur_day_cnsmp_amt ,
    a.card_nb_cur_day_out_num ,
    a.card_nb_cur_day_out_amt ,
    a.card_mb_cur_day_out_num ,
    a.card_mb_cur_day_out_amt ,
    a.card_all_7_day_trade_num ,
    a.card_all_7_day_trade_amt ,
    a.card_all_7_day_in_num ,
    a.card_all_7_day_in_amt ,
    a.card_all_7_day_out_num ,
    a.card_all_7_day_out_amt ,
    a.card_all_7_day_trn_out_num ,
    a.card_all_7_day_trn_out_amt ,
    a.card_all_7_day_500_out_num ,
    a.card_all_7_day_500_out_amt ,
    a.card_all_7_day_10000_out_num ,
    a.card_all_7_day_10000_out_amt ,
    a.card_all_7_day_20000_out_num ,
    a.card_all_7_day_20000_out_amt ,
    a.card_all_7_day_more_out_num ,
    a.card_all_7_day_more_out_amt ,
    a.card_atm_7_day_dep_num ,
    a.card_atm_7_day_dep_amt ,
    a.card_atm_7_day_wd_num ,
    a.card_atm_7_day_wd_amt ,
    a.card_atm_7_day_trn_num ,
    a.card_atm_7_day_trn_amt ,
    a.card_pos_7_day_cnsmp_num ,
    a.card_pos_7_day_cnsmp_amt ,
    a.card_nb_7_day_out_num ,
    a.card_nb_7_day_out_amt ,
    a.card_mb_7_day_out_num ,
    a.card_mb_7_day_out_amt ,
    a.card_all_30_day_trade_num ,
    a.card_all_30_day_trade_amt ,
    a.card_all_30_day_in_num ,
    a.card_all_30_day_in_amt ,
    a.card_all_30_day_out_num ,
    a.card_all_30_day_out_amt ,
    a.card_all_30_day_trn_out_num ,
    a.card_all_30_day_trn_out_amt ,
    a.card_all_30_day_500_out_num ,
    a.card_all_30_day_500_out_amt ,
    a.card_all_30_day_10000_out_num ,
    a.card_all_30_day_10000_out_amt ,
    a.card_all_30_day_20000_out_num ,
    a.card_all_30_day_20000_out_amt ,
    a.card_all_30_day_more_out_num ,
    a.card_all_30_day_more_out_amt ,
    a.card_atm_30_day_dep_num ,
    a.card_atm_30_day_dep_amt ,
    a.card_atm_30_day_wd_num ,
    a.card_atm_30_day_wd_amt ,
    a.card_atm_30_day_trn_num ,
    a.card_atm_30_day_trn_amt ,
    a.card_pos_30_day_cnsmp_num ,
    a.card_pos_30_day_cnsmp_amt ,
    a.card_nb_30_day_out_num ,
    a.card_nb_30_day_out_amt ,
    a.card_mb_30_day_out_num ,
    a.card_mb_30_day_out_amt ,
    a.card_all_90_day_trade_num ,
    a.card_all_90_day_trade_amt ,
    a.card_all_90_day_in_num ,
    a.card_all_90_day_in_amt ,
    a.card_all_90_day_out_num ,
    a.card_all_90_day_out_amt ,
    a.card_all_90_day_trn_out_num ,
    a.card_all_90_day_trn_out_amt ,
    a.card_all_90_day_500_out_num ,
    a.card_all_90_day_500_out_amt ,
    a.card_all_90_day_10000_out_num ,
    a.card_all_90_day_10000_out_amt ,
    a.card_all_90_day_20000_out_num ,
    a.card_all_90_day_20000_out_amt ,
    a.card_all_90_day_more_out_num ,
    a.card_all_90_day_more_out_amt ,
    a.card_atm_90_day_dep_num ,
    a.card_atm_90_day_dep_amt ,
    a.card_atm_90_day_wd_num ,
    a.card_atm_90_day_wd_amt ,
    a.card_atm_90_day_trn_num ,
    a.card_atm_90_day_trn_amt ,
    a.card_pos_90_day_cnsmp_num ,
    a.card_pos_90_day_cnsmp_amt ,
    a.card_nb_90_day_out_num ,
    a.card_nb_90_day_out_amt ,
    a.card_mb_90_day_out_num ,
    a.card_mb_90_day_out_amt ,
    a.pass_all_cur_day_trade_num ,
    a.pass_all_cur_day_trade_amt ,
    a.pass_all_cur_day_in_num ,
    a.pass_all_cur_day_in_amt ,
    a.pass_all_cur_day_out_num ,
    a.pass_all_cur_day_out_amt ,
    a.pass_all_cur_day_trn_out_num ,
    a.pass_all_cur_day_trn_out_amt ,
    a.pass_all_cur_day_500_out_num ,
    a.pass_all_cur_day_500_out_amt ,
    a.pass_all_cur_day_10000_out_num ,
    a.pass_all_cur_day_10000_out_amt ,
    a.pass_all_cur_day_20000_out_num ,
    a.pass_all_cur_day_20000_out_amt ,
    a.pass_all_cur_day_more_out_num ,
    a.pass_all_cur_day_more_out_amt ,
    a.pass_atm_cur_day_dep_num ,
    a.pass_atm_cur_day_dep_amt ,
    a.pass_atm_cur_day_wd_num ,
    a.pass_atm_cur_day_wd_amt ,
    a.pass_atm_cur_day_trn_num ,
    a.pass_atm_cur_day_trn_amt ,
    a.pass_pos_cur_day_cnsmp_num ,
    a.pass_pos_cur_day_cnsmp_amt ,
    a.pass_nb_cur_day_out_num ,
    a.pass_nb_cur_day_out_amt ,
    a.pass_mb_cur_day_out_num ,
    a.pass_mb_cur_day_out_amt ,
    a.pass_all_7_day_trade_num ,
    a.pass_all_7_day_trade_amt ,
    a.pass_all_7_day_in_num ,
    a.pass_all_7_day_in_amt ,
    a.pass_all_7_day_out_num ,
    a.pass_all_7_day_out_amt ,
    a.pass_all_7_day_trn_out_num ,
    a.pass_all_7_day_trn_out_amt ,
    a.pass_all_7_day_500_out_num ,
    a.pass_all_7_day_500_out_amt ,
    a.pass_all_7_day_10000_out_num ,
    a.pass_all_7_day_10000_out_amt ,
    a.pass_all_7_day_20000_out_num ,
    a.pass_all_7_day_20000_out_amt ,
    a.pass_all_7_day_more_out_num ,
    a.pass_all_7_day_more_out_amt ,
    a.pass_atm_7_day_dep_num ,
    a.pass_atm_7_day_dep_amt ,
    a.pass_atm_7_day_wd_num ,
    a.pass_atm_7_day_wd_amt ,
    a.pass_atm_7_day_trn_num ,
    a.pass_atm_7_day_trn_amt ,
    a.pass_pos_7_day_cnsmp_num ,
    a.pass_pos_7_day_cnsmp_amt ,
    a.pass_nb_7_day_out_num ,
    a.pass_nb_7_day_out_amt ,
    a.pass_mb_7_day_out_num ,
    a.pass_mb_7_day_out_amt ,
    a.pass_all_30_day_trade_num ,
    a.pass_all_30_day_trade_amt ,
    a.pass_all_30_day_in_num ,
    a.pass_all_30_day_in_amt ,
    a.pass_all_30_day_out_num ,
    a.pass_all_30_day_out_amt ,
    a.pass_all_30_day_trn_out_num ,
    a.pass_all_30_day_trn_out_amt ,
    a.pass_all_30_day_500_out_num ,
    a.pass_all_30_day_500_out_amt ,
    a.pass_all_30_day_10000_out_num ,
    a.pass_all_30_day_10000_out_amt ,
    a.pass_all_30_day_20000_out_num ,
    a.pass_all_30_day_20000_out_amt ,
    a.pass_all_30_day_more_out_num ,
    a.pass_all_30_day_more_out_amt ,
    a.pass_atm_30_day_dep_num ,
    a.pass_atm_30_day_dep_amt ,
    a.pass_atm_30_day_wd_num ,
    a.pass_atm_30_day_wd_amt ,
    a.pass_atm_30_day_trn_num ,
    a.pass_atm_30_day_trn_amt ,
    a.pass_pos_30_day_cnsmp_num ,
    a.pass_pos_30_day_cnsmp_amt ,
    a.pass_nb_30_day_out_num ,
    a.pass_nb_30_day_out_amt ,
    a.pass_mb_30_day_out_num ,
    a.pass_mb_30_day_out_amt ,
    a.pass_all_90_day_trade_num ,
    a.pass_all_90_day_trade_amt ,
    a.pass_all_90_day_in_num ,
    a.pass_all_90_day_in_amt ,
    a.pass_all_90_day_out_num ,
    a.pass_all_90_day_out_amt ,
    a.pass_all_90_day_trn_out_num ,
    a.pass_all_90_day_trn_out_amt ,
    a.pass_all_90_day_500_out_num ,
    a.pass_all_90_day_500_out_amt ,
    a.pass_all_90_day_10000_out_num ,
    a.pass_all_90_day_10000_out_amt ,
    a.pass_all_90_day_20000_out_num ,
    a.pass_all_90_day_20000_out_amt ,
    a.pass_all_90_day_more_out_num ,
    a.pass_all_90_day_more_out_amt ,
    a.pass_atm_90_day_dep_num ,
    a.pass_atm_90_day_dep_amt ,
    a.pass_atm_90_day_wd_num ,
    a.pass_atm_90_day_wd_amt ,
    a.pass_atm_90_day_trn_num ,
    a.pass_atm_90_day_trn_amt ,
    a.pass_pos_90_day_cnsmp_num ,
    a.pass_pos_90_day_cnsmp_amt ,
    a.pass_nb_90_day_out_num ,
    a.pass_nb_90_day_out_amt ,
    a.pass_mb_90_day_out_num ,
    a.pass_mb_90_day_out_amt ,
    a.p9_data_date
from ${db}.train_feature_trad_flow_a a
inner join top1000_crdtno_flow_no b
  on  concat(a.SA_ACCT_NO, '_', a.SA_DDP_ACCT_NO_DET_N) = b.flow_no;
!
}


spark_predict()
{
data_date=$1

num_executors=30
executor_memory=8G
executor_cores=5
driver_memory=16G

spark-submit \
--master yarn \
--deploy-mode cluster \
--num-executors $num_executors \
--driver-memory $driver_memory \
--executor-cores $executor_cores \
--executor-memory $executor_memory \
../baidu/ccb_risk_scoring_opt.jar Predict 0.90 "${db}:train_feature_trad_flow_a_${batch}_${data_date}: " hdfs://hacluster/ccb_risk_scoring/model_data/20170109/model7 train_feature_trad_flow_a_mark_predict_${batch}_${data_date}
}

#for date in 20160423 20160422 20160421; do
for date in 20170327; do
   create_table $date
   insert $date
   spark_predict $date
done


