use sor;

-- Hive建表脚本
-- 客户排队信息表: ILLEGAL_CUST_QUEUE_INFO_TMP, ILLEGAL_CUST_QUEUE_INFO


-- 临时表
DROP TABLE IF EXISTS ILLEGAL_CUST_QUEUE_INFO_TMP;

CREATE EXTERNAL TABLE IF NOT EXISTS ILLEGAL_CUST_QUEUE_INFO_TMP(
  TX_DT STRING,
  PASS_NUM STRING
)
PARTITIONED BY (P9_DATA_DATE string)
STORED AS ORC;


-- 最终表

DROP TABLE IF EXISTS ILLEGAL_CUST_QUEUE_INFO;

CREATE EXTERNAL TABLE IF NOT EXISTS ILLEGAL_CUST_QUEUE_INFO(
  TX_DT STRING,
  PASS_NUM STRING
)
PARTITIONED BY (P9_DATA_DATE string)
STORED AS ORC;