use sor;

-- Hive建表脚本
-- P2LOG 无卡异地查询分析表


--(1)查询无卡信息
DROP TABLE IF EXISTS ILLEGAL_P2NOCARD;

CREATE EXTERNAL TABLE IF NOT EXISTS ILLEGAL_P2NOCARD(
  TX_DATE STRING,
  TX_TIME STRING,
  TX_CODE STRING,
  OPER_CODE STRING,
  OPER_NAME STRING,
  TERMINAL_MAC STRING,
  TERMINAL_IP STRING,
  ORG_SHORT_CNAME STRING,
  INST_LEVEL1_BRANCH_ID STRING,
  BRANCH_ID STRING,
  CST_ID STRING,
  FS_ACCT_NO STRING,
  ID_CRDT_NO STRING

)
PARTITIONED BY (P9_DATA_DATE string)
STORED AS ORC;


--(2)通过 卡号、身份证、客户号 补全信息
DROP TABLE IF EXISTS ILLEGAL_P2NOCARD_CUST_INFO;

CREATE EXTERNAL TABLE IF NOT EXISTS ILLEGAL_P2NOCARD_CUST_INFO(
  TX_DATE STRING,
  TX_TIME STRING,
  TX_CODE STRING,
  OPER_CODE STRING,
  OPER_NAME STRING,
  TERMINAL_MAC STRING,
  TERMINAL_IP STRING,
  ORG_SHORT_CNAME STRING,
  INST_LEVEL1_BRANCH_ID STRING,
  BRANCH_ID STRING,
  CST_ID STRING,
  PASS_NUM STRING,
  FS_ACCT_NO STRING,
  CARD_NO STRING
)
PARTITIONED BY (P9_DATA_DATE string)
STORED AS ORC;


--(3)通过银行卡号，获取银行卡开户机构 获取无卡查询机构对比信息
DROP TABLE IF EXISTS ILLEGAL_P2NOCARD_OPUN;

CREATE EXTERNAL TABLE IF NOT EXISTS ILLEGAL_P2NOCARD_OPUN(
  TX_DATE STRING,
  TX_TIME STRING,
  TX_CODE STRING,
  OPER_CODE STRING,
  OPER_NAME STRING,
  TERMINAL_MAC STRING,
  TERMINAL_IP STRING,
  ORG_SHORT_CNAME STRING,
  INST_LEVEL1_BRANCH_ID STRING,
  BRANCH_ID STRING,
  CST_ID STRING,
  PASS_NUM STRING,
  FS_ACCT_NO STRING,
  CARD_NO STRING,
  
  CR_OPUN_COD STRING,
  SAME STRING
)
PARTITIONED BY (P9_DATA_DATE string)
STORED AS ORC;



--(4)获取异地无卡查询的客户
DROP TABLE IF EXISTS ILLEGAL_P2NOCARD_NOSAME_PASSNUM;

CREATE EXTERNAL TABLE IF NOT EXISTS ILLEGAL_P2NOCARD_NOSAME_PASSNUM(
  TX_DATE STRING,
  TX_TIME STRING,
  OPER_CODE STRING,
  PASS_NUM STRING,
  IS_SAME STRING
)
PARTITIONED BY (P9_DATA_DATE string)
STORED AS ORC;


--(5)获取异地无卡查询的明细
DROP TABLE IF EXISTS ILLEGAL_P2NOCARD_NOSAME_A;

CREATE EXTERNAL TABLE IF NOT EXISTS ILLEGAL_P2NOCARD_NOSAME_A(
  TX_DATE STRING,
  TX_TIME STRING,
  TX_CODE STRING,
  OPER_CODE STRING,
  OPER_NAME STRING,
  TERMINAL_MAC STRING,
  TERMINAL_IP STRING,
  ORG_SHORT_CNAME STRING,
  BRANCH_ID STRING,
  CST_ID STRING,
  PASS_NUM STRING,
  FS_ACCT_NO STRING,
  CARD_NO STRING,
  CR_OPUN_COD STRING
)
PARTITIONED BY (P9_DATA_DATE string)
STORED AS ORC;


--(6)获取异地无卡查询的明细+客户机构信息
DROP TABLE IF EXISTS ILLEGAL_P2NOCARD_NOSAME_A_CUSTORG;

CREATE EXTERNAL TABLE IF NOT EXISTS ILLEGAL_P2NOCARD_NOSAME_A_CUSTORG(
  TX_DATE STRING,
  TX_TIME STRING,
  TX_CODE STRING,
  OPER_CODE STRING,
  OPER_NAME STRING,
  TERMINAL_MAC STRING,
  TERMINAL_IP STRING,
  ORG_SHORT_CNAME STRING,
  BRANCH_ID STRING,
  CST_ID STRING,
  PASS_NUM STRING,
  FS_ACCT_NO STRING,
  CARD_NO STRING,
  CR_OPUN_COD STRING,
  
  CR_OPUN_NM STRING
)
PARTITIONED BY (P9_DATA_DATE string)
STORED AS ORC;



--(7)获取异地无卡查询的明细+柜员机构信息
DROP TABLE IF EXISTS ILLEGAL_P2NOCARD_NOSAME_A_OPERORG;

CREATE EXTERNAL TABLE IF NOT EXISTS ILLEGAL_P2NOCARD_NOSAME_A_OPERORG(
  TX_DATE STRING,
  TX_TIME STRING,
  TX_CODE STRING,
  OPER_CODE STRING,
  OPER_NAME STRING,
  TERMINAL_MAC STRING,
  TERMINAL_IP STRING,
  ORG_SHORT_CNAME STRING,
  BRANCH_ID STRING,
  CST_ID STRING,
  PASS_NUM STRING,
  FS_ACCT_NO STRING,
  CARD_NO STRING,
  CR_OPUN_COD STRING,
  CR_OPUN_NM STRING,
  
  CM_OPR_NAME STRING,
  CM_OPUN_CODE STRING,
  CCBINS_CHN_SHRTNM STRING,
  PARENT_ID STRING,
  PARENT_CHN_SHRTNM STRING
)
PARTITIONED BY (P9_DATA_DATE string)
STORED AS ORC;


--(8)统计信息
DROP TABLE IF EXISTS ILLEGAL_P2NOCARD_A;

CREATE EXTERNAL TABLE IF NOT EXISTS ILLEGAL_P2NOCARD_A(
  TX_DATE STRING,
  OPER_CODE STRING,
  CM_OPR_NAME STRING,
  CM_OPUN_CODE STRING,
  CCBINS_CHN_SHRTNM STRING,
  PARENT_ID STRING,
  PARENT_CHN_SHRTNM STRING,
  NUM STRING
)
PARTITIONED BY (P9_DATA_DATE string)
STORED AS ORC;