use sor;

-- Hive建表脚本
-- pbcs系统 无卡异地查询分析表
--ILLEGAL_PBCS_PASSNUM ： 通过卡号、身份证补全 身份证信息


--(1)通过卡号、身份证补全 身份证信息
DROP TABLE IF EXISTS ILLEGAL_PBCS_PASSNUM;

CREATE EXTERNAL TABLE IF NOT EXISTS ILLEGAL_PBCS_PASSNUM(
  TX_DT STRING,
  BRANCH_IDASQUERY_ORG STRING,
  DEBIT_ACCT_NUM STRING,
  CARD_NO STRING,
  CUSTOMER_NAME STRING,
  CR_OPUN_COD STRING,
  DEBIT_CUSTOMER_NUMASCUST_NO STRING,
  TX_DTASQUE_DATE STRING,
  TX_OPERATOR STRING,
  ID_CRDT_NOASCRDT_NO STRING,
  BRANCH_ID STRING,

  ID_CRDT_NO STRING,
  CARD_NO STRING
)
PARTITIONED BY (P9_DATA_DATE string)
STORED AS ORC;


--(2)补全卡卡户机构
DROP TABLE IF EXISTS ILLEGAL_PBCS_OPUN;

CREATE EXTERNAL TABLE IF NOT EXISTS ILLEGAL_PBCS_OPUN(
 TX_DT STRING,
  BRANCH_IDASQUERY_ORG STRING,
  DEBIT_ACCT_NUM STRING,
  CARD_NO STRING,
  CUSTOMER_NAME STRING,
  CR_OPUN_COD STRING,
  DEBIT_CUSTOMER_NUMASCUST_NO STRING,
  TX_DTASQUE_DATE STRING,
  TX_OPERATOR STRING,
  ID_CRDT_NOASCRDT_NO STRING,
  BRANCH_ID STRING,

  ID_CRDT_NO STRING,
  CARD_NO STRING,
  CR_OPUN_COD STRING,
  CUSTOMER_NAME STRING
)
PARTITIONED BY (P9_DATA_DATE string)
STORED AS ORC;



--(3)补全同地异地标志
DROP TABLE IF EXISTS ILLEGAL_PBCS_SAME;

CREATE EXTERNAL TABLE IF NOT EXISTS ILLEGAL_PBCS_SAME(
  TX_DT STRING,
  BRANCH_IDASQUERY_ORG STRING,
  DEBIT_ACCT_NUM STRING,
  CARD_NO STRING,
  CUSTOMER_NAME STRING,
  CR_OPUN_COD STRING,
  DEBIT_CUSTOMER_NUMASCUST_NO STRING,
  TX_DTASQUE_DATE STRING,
  TX_OPERATOR STRING,
  ID_CRDT_NOASCRDT_NO STRING,
  BRANCH_ID STRING,

  ID_CRDT_NO STRING,
  CARD_NO STRING,
  CR_OPUN_COD STRING,
  CUSTOMER_NAME STRING,
  SAME STRING
)
PARTITIONED BY (P9_DATA_DATE string)
STORED AS ORC;


--(4)查询出异地的客户信息
DROP TABLE IF EXISTS ILLEGAL_PBCS_NOSAME;

CREATE EXTERNAL TABLE IF NOT EXISTS ILLEGAL_PBCS_NOSAME(
  QUE_DATE STRING,
   TLR_ID STRING,
   CRDT_NO STRING,
   IS_SAME STRING
)
PARTITIONED BY (P9_DATA_DATE string)
STORED AS ORC;


--(5)查询出异地的查询交易明细
DROP TABLE IF EXISTS ILLEGAL_PBCS_NOSAME_A;

CREATE EXTERNAL TABLE IF NOT EXISTS ILLEGAL_PBCS_NOSAME_A(
  QUE_DATE STRING,
  TLR_ID STRING,
  QUERY_ORG STRING,
  DEBIT_ACCT_NUM STRING,
  CARD_NO STRING,
  CUSTOMER_NAME STRING,
  CR_OPUN_COD STRING,
  CUST_NO STRING,
  CRDT_NO STRING
)
PARTITIONED BY (P9_DATA_DATE string)
STORED AS ORC;



--(6)查询出异地查询 且 不在排队机的交易明细
DROP TABLE IF EXISTS ILLEGAL_PBCS_NOSAME_NOQUEUE;

CREATE EXTERNAL TABLE IF NOT EXISTS ILLEGAL_PBCS_NOSAME_NOQUEUE(
  QUE_DATE STRING,
  TLR_ID STRING,
  QUERY_ORG STRING,
  CUST_NO STRING,
  CUSTOMER_NAME STRING,
  DEBIT_ACCT_NUM STRING,
  CARD_NO STRING,
  CRDT_NO STRING
)
PARTITIONED BY (P9_DATA_DATE string)
STORED AS ORC;


--(7)查询出异地查询 且 不在排队机的交易明细
DROP TABLE IF EXISTS ILLEGAL_PBCS_OPUNNAME;

CREATE EXTERNAL TABLE IF NOT EXISTS ILLEGAL_PBCS_OPUNNAME(
  QUE_DATE STRING,
  TLR_ID STRING,
  QUERY_ORG STRING,
  CUST_NO STRING,
  CUSTOMER_NAME STRING,
  DEBIT_ACCT_NUM STRING,
  CARD_NO STRING,
  CRDT_NO STRING,
  CR_OPUN_NM STRING
)
PARTITIONED BY (P9_DATA_DATE string)
STORED AS ORC;

--(8)添加柜员身份证号
DROP TABLE IF EXISTS ILLEGAL_PBCS_OPER_PASSNUM;

CREATE EXTERNAL TABLE IF NOT EXISTS ILLEGAL_PBCS_OPER_PASSNUM(
  QUE_DATE STRING,
  TLR_ID STRING,
  QUERY_ORG STRING,
  CUST_NO STRING,
  CUSTOMER_NAME STRING,
  DEBIT_ACCT_NUM STRING,
  CARD_NO STRING,
  CRDT_NO STRING,
  CR_OPUN_NM STRING,
  CM_id_NO STRING
)
PARTITIONED BY (P9_DATA_DATE string)
STORED AS ORC;


--(9)获取员工名称，与员工所在网点号及网点名
DROP TABLE IF EXISTS ILLEGAL_PBCS_OPER_INFO;

CREATE EXTERNAL TABLE IF NOT EXISTS ILLEGAL_PBCS_OPER_INFO(
  QUE_DATE STRING,
  TLR_ID STRING,
  QUERY_ORG STRING,
  CUST_NO STRING,
  CUSTOMER_NAME STRING,
  DEBIT_ACCT_NUM STRING,
  CARD_NO STRING,
  CRDT_NO STRING,
  CR_OPUN_NM STRING,
  CM_id_NO STRING,
  CM_OPR_NAME STRING,
  CM_OPUN_CODE STRING,
  CCBINS_CHN_SHRTNM STRING
)
PARTITIONED BY (P9_DATA_DATE string)
STORED AS ORC;


--(10)获取员工网点的父亲机构
DROP TABLE IF EXISTS ILLEGAL_PBCS_OPER_PARENT;

CREATE EXTERNAL TABLE IF NOT EXISTS ILLEGAL_PBCS_OPER_PARENT(
  QUE_DATE STRING,
  TLR_ID STRING,
  QUERY_ORG STRING,
  CUST_NO STRING,
  CUSTOMER_NAME STRING,
  DEBIT_ACCT_NUM STRING,
  CARD_NO STRING,
  CRDT_NO STRING,
  CR_OPUN_NM STRING,
  CM_id_NO STRING,
  CM_OPR_NAME STRING,
  CM_OPUN_CODE STRING,
  CCBINS_CHN_SHRTNM STRING,
  PARENT_ID STRING,
  PARENT_CHN_SHRTNM STRING
)
PARTITIONED BY (P9_DATA_DATE string)
STORED AS ORC;



--(11过滤客户没做ATM_非账务等交易的明细。
DROP TABLE IF EXISTS ILLEGAL_PBCS_NOREFINE;

CREATE EXTERNAL TABLE IF NOT EXISTS ILLEGAL_PBCS_NOREFINE(
  QUE_DATE STRING,
  TLR_ID STRING,
  QUERY_ORG STRING,
  CUST_NO STRING,
  CUSTOMER_NAME STRING,
  DEBIT_ACCT_NUM STRING,
  CARD_NO STRING,
  CRDT_NO STRING,
  CR_OPUN_NM STRING,
  CM_id_NO STRING,
  CM_OPR_NAME STRING,
  CM_OPUN_CODE STRING,
  CCBINS_CHN_SHRTNM STRING,
  PARENT_ID STRING,
  PARENT_CHN_SHRTNM STRING
)
PARTITIONED BY (P9_DATA_DATE string)
STORED AS ORC;



--(12)按日期统计查询量
DROP TABLE IF EXISTS ILLEGAL_PBCS_NOREFINE;

CREATE EXTERNAL TABLE IF NOT EXISTS ILLEGAL_PBCS_NOREFINE(
  QUE_DATE STRING,
  TLR_ID STRING,
  CM_ID_NO STRING,
  CM_OPR_NAME STRING,
  QUERY_ORG STRING,
  CM_OPUN_CODE STRING,
  CCBINS_CHN_SHRTNM STRING,
  PARENT_ID STRING,
  PARENT_CHN_SHRTNM STRING,
  NUM STRING
)
PARTITIONED BY (P9_DATA_DATE string)
STORED AS ORC;